# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindowGUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1013, 900)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 900))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        MainWindow.setStyleSheet("/*\n"
"* Description : 白色靓丽\n"
"*/\n"
"\n"
"/**********子界面背景**********/\n"
"/*QWidget#customWidget {\n"
"        background: rgb(173, 202, 232);\n"
"}\n"
"\n"
"/**********子界面中央背景**********/\n"
"/*QWidget#centerWidget {\n"
"        background: rgb(232, 241, 252);\n"
"}\n"
"\n"
"/**********主界面样式**********/\n"
"/*QWidget#mainWindow_dockWidget {\n"
"        border: 1px solid rgb(111, 156, 207);\n"
"        \n"
"    background: rgb(232, 241, 252);\n"
"}\n"
"\n"
"QWidget#messageWidget {\n"
"        background: rgba(173, 202, 232, 50%);\n"
"}\n"
"\n"
"QWidget#loadingWidget {\n"
"        border: none;\n"
"        border-radius: 5px;\n"
"        background: rgb(187, 212, 238);\n"
"\n"
"}\n"
"\n"
"QWidget#remoteWidget {\n"
"        border-top-right-radius: 10px;\n"
"        border-bottom-right-radius: 10px;\n"
"        border: 1px solid rgb(111, 156, 207);\n"
"        border-left: none;\n"
"        background: transparent;\n"
"}*/\n"
"\n"
"StyledWidget {\n"
"        qproperty-normalColor: rgb(65, 65, 65);\n"
"        qproperty-disableColor: rgb(180, 180, 180);\n"
"        qproperty-highlightColor: rgb(0, 160, 230);\n"
"        qproperty-errorColor: red;\n"
"}\n"
"\n"
"QProgressIndicator {\n"
"        qproperty-color: rgb(2, 65, 132);\n"
"}\n"
"\n"
"/**********提示**********/\n"
"QToolTip{\n"
"        border: 1px solid rgb(111, 156, 207);\n"
"        background: white;\n"
"        color: rgb(51, 51, 51);\n"
"}\n"
"\n"
"/**********菜单栏**********/\n"
"QMenuBar {\n"
"        background: rgb(187, 212, 238);\n"
"        border: 1px solid rgb(111, 156, 207);\n"
"        border-left: none;\n"
"        border-right: none;\n"
"}\n"
"QMenuBar::item {\n"
"        border: 1px solid transparent;\n"
"        padding: 5px 10px 5px 10px;\n"
"        background: transparent;\n"
"}\n"
"QMenuBar::item:enabled {\n"
"        color: rgb(2, 65, 132);\n"
"}\n"
"QMenuBar::item:!enabled {\n"
"        color: rgb(155, 155, 155);\n"
"}\n"
"QMenuBar::item:enabled:selected {\n"
"        border-top-color: rgb(111, 156, 207);\n"
"        border-bottom-color: rgb(111, 156, 207);\n"
"        background: rgb(198, 224, 252);\n"
"}\n"
"\n"
"/**********菜单**********/\n"
"QMenu {\n"
"        border: 1px solid rgb(111, 156, 207);\n"
"        background: rgb(232, 241, 250);\n"
"}\n"
"QMenu::item {\n"
"        height: 22px;\n"
"        padding: 0px 25px 0px 20px;\n"
"}\n"
"QMenu::item:enabled {\n"
"        color: rgb(84, 84, 84);\n"
"}\n"
"QMenu::item:!enabled {\n"
"        color: rgb(155, 155, 155);\n"
"}\n"
"QMenu::item:enabled:selected {\n"
"        color: rgb(2, 65, 132);\n"
"        background: rgba(255, 255, 255, 200);\n"
"}\n"
"QMenu::separator {\n"
"        height: 1px;\n"
"        background: rgb(111, 156, 207);\n"
"}\n"
"QMenu::indicator {\n"
"        width: 13px;\n"
"        height: 13px;\n"
"}\n"
"QMenu::icon {\n"
"        padding-left: 2px;\n"
"        padding-right: 2px;\n"
"}\n"
"\n"
"/**********状态栏**********/\n"
"QStatusBar {\n"
"        background: rgb(187, 212, 238);\n"
"        border: 1px solid rgb(111, 156, 207);\n"
"        border-left: none;\n"
"        border-right: none;\n"
"        border-bottom: none;\n"
"}\n"
"QStatusBar::item {\n"
"    border: none;\n"
"    border-right: 1px solid rgb(111, 156, 207);\n"
"}\n"
"\n"
"/**********分组框**********/\n"
"QGroupBox {\n"
"        font-size: 15px;\n"
"        border: 1px solid rgb(111, 156, 207);\n"
"        border-radius: 4px;\n"
"        margin-top: 13px;\n"
"}\n"
"QGroupBox::title {\n"
"        color: rgb(56, 99, 154);\n"
"        top: -12px;\n"
"        left: 10px;\n"
"}\n"
"\n"
"/**********页签项**********/\n"
"QTabWidget::pane {\n"
"        border: none;\n"
"        border-top: 3px solid rgb(0, 78, 161);\n"
"        background: rgb(187, 212, 238);\n"
"}\n"
"QTabWidget::tab-bar {\n"
"        border: none;\n"
"}\n"
"QTabBar::tab {\n"
"        border: none;\n"
"        border-top-left-radius: 1px;\n"
"        border-top-right-radius: 1px;\n"
"        color: white;\n"
"        background: rgb(120, 170, 220);\n"
"        height: 28px;\n"
"        min-width: 85px;\n"
"        \n"
"}\n"
"QTabBar::tab:hover {\n"
"        background: rgb(0, 78, 161);\n"
"}\n"
"QTabBar::tab:selected {\n"
"        color: white;\n"
"        background: rgb(0, 78, 161);\n"
"}\n"
"\n"
"QTabWidget#tabWidget::pane {\n"
"        border: 1px solid rgb(111, 156, 207);\n"
"        background: rgb(232, 241, 252);\n"
"        margin-top: -1px;\n"
"}\n"
"\n"
"QTabBar#tabBar::tab {\n"
"        border: 1px solid rgb(111, 156, 207);\n"
"        border-bottom: none;\n"
"        color: rgb(70, 71, 73);\n"
"        background: transparent;\n"
"}\n"
"QTabBar#tabBar::tab:hover {\n"
"        color: rgb(2, 65, 132);\n"
"}\n"
"QTabBar#tabBar::tab:selected {\n"
"        color: rgb(2, 65, 132);\n"
"        background: rgb(232, 241, 252);\n"
"}\n"
"\n"
"/**********表头**********/\n"
"QHeaderView{\n"
"        border: none;\n"
"        border-bottom: 3px solid rgb(0, 78, 161);\n"
"        background: transparent;\n"
"        min-height: 30px;\n"
"}\n"
"QHeaderView::section:horizontal {\n"
"        border: none;\n"
"        color: rgb(2, 65, 132);\n"
"        background: transparent;\n"
"        padding-left: 5px;\n"
"}\n"
"QHeaderView::section:horizontal:hover {\n"
"        color: white;\n"
"        background: rgb(0, 78, 161);\n"
"}\n"
"QHeaderView::section:horizontal:pressed {\n"
"        color: white;\n"
"        background: rgb(6, 94, 187);\n"
"}\n"
"QHeaderView::up-arrow {\n"
"        width: 13px;\n"
"        height: 11px;\n"
"        padding-right: 5px;\n"
"        image: url(:/White/topArrow);\n"
"        subcontrol-position: center right;\n"
"}\n"
"QHeaderView::up-arrow:hover, QHeaderView::up-arrow:pressed {\n"
"        image: url(:/White/topArrowHover);\n"
"}\n"
"QHeaderView::down-arrow {\n"
"        width: 13px;\n"
"        height: 11px;\n"
"        padding-right: 5px;\n"
"        image: url(:/White/bottomArrow);\n"
"        subcontrol-position: center right;\n"
"}\n"
"QHeaderView::down-arrow:hover, QHeaderView::down-arrow:pressed {\n"
"        image: url(:/White/bottomArrowHover);\n"
"}\n"
"\n"
"/**********表格**********/\n"
"QTableView {\n"
"        border: 1px solid rgb(111, 156, 207);\n"
"        background: rgb(224, 238, 255);\n"
"        gridline-color: rgb(111, 156, 207);\n"
"}\n"
"QTableView::item {\n"
"        padding-left: 5px;\n"
"        padding-right: 5px;\n"
"        border: none;\n"
"        background: white;\n"
"        border-right: 1px solid rgb(111, 156, 207);\n"
"        border-bottom: 1px solid rgb(111, 156, 207);\n"
"}\n"
"QTableView::item:selected {\n"
"        background: rgba(255, 255, 255, 100);\n"
"}\n"
"QTableView::item:selected:!active {\n"
"        color: rgb(65, 65, 65);\n"
"}\n"
"QTableView::indicator {\n"
"        width: 20px;\n"
"        height: 20px;\n"
"}\n"
"QTableView::indicator:enabled:unchecked {\n"
"        image: url(:/White/checkBox);\n"
"}\n"
"QTableView::indicator:enabled:unchecked:hover {\n"
"        image: url(:/White/checkBoxHover);\n"
"}\n"
"QTableView::indicator:enabled:unchecked:pressed {\n"
"        image: url(:/White/checkBoxPressed);\n"
"}\n"
"QTableView::indicator:enabled:checked {\n"
"        image: url(:/White/checkBoxChecked);\n"
"}\n"
"QTableView::indicator:enabled:checked:hover {\n"
"        image: url(:/White/checkBoxCheckedHover);\n"
"}\n"
"QTableView::indicator:enabled:checked:pressed {\n"
"        image: url(:/White/checkBoxCheckedPressed);\n"
"}\n"
"QTableView::indicator:enabled:indeterminate {\n"
"        image: url(:/White/checkBoxIndeterminate);\n"
"}\n"
"QTableView::indicator:enabled:indeterminate:hover {\n"
"        image: url(:/White/checkBoxIndeterminateHover);\n"
"}\n"
"QTableView::indicator:enabled:indeterminate:pressed {\n"
"        image: url(:/White/checkBoxIndeterminatePressed);\n"
"}\n"
"\n"
"/**********滚动条-水平**********/\n"
"QScrollBar:horizontal {\n"
"        height: 20px;\n"
"        background: transparent;\n"
"        margin-top: 3px;\n"
"        margin-bottom: 3px;\n"
"}\n"
"QScrollBar::handle:horizontal {\n"
"        height: 20px;\n"
"        min-width: 30px;\n"
"        background: rgb(170, 200, 230);\n"
"        margin-left: 15px;\n"
"        margin-right: 15px;\n"
"}\n"
"QScrollBar::handle:horizontal:hover {\n"
"        background: rgb(165, 195, 225);\n"
"}\n"
"QScrollBar::sub-line:horizontal {\n"
"        width: 12px;\n"
"        background: transparent;\n"
"    image: url(:/pngicon/Resources/left_change.png);\n"
"        subcontrol-position: left;\n"
"}\n"
"QScrollBar::add-line:horizontal {\n"
"        width: 12px;\n"
"        background: transparent;\n"
"        \n"
"    image: url(:/pngicon/Resources/right_change.png);\n"
"        subcontrol-position: right;\n"
"}\n"
"QScrollBar::sub-line:horizontal:hover {\n"
"        background: rgb(170, 200, 230);\n"
"}\n"
"QScrollBar::add-line:horizontal:hover {\n"
"        background: rgb(170, 200, 230);\n"
"}\n"
"QScrollBar::add-page:horizontal,QScrollBar::sub-page:horizontal {\n"
"        background: transparent;\n"
"}\n"
"\n"
"/**********滚动条-垂直**********/\n"
"QScrollBar:vertical {\n"
"        width: 20px;\n"
"        background: transparent;\n"
"        margin-left: 3px;\n"
"        margin-right: 3px;\n"
"}\n"
"QScrollBar::handle:vertical {\n"
"        width: 20px;\n"
"        min-height: 20px;\n"
"        background: rgb(170, 200, 230);\n"
"        margin-top: 10px;\n"
"        margin-bottom:10px;\n"
"}\n"
"QScrollBar::handle:vertical:hover {\n"
"        background: rgb(165, 195, 225);\n"
"}\n"
"QScrollBar::sub-line:vertical {\n"
"        height:7px;\n"
"        background: rgb(255, 255, 255);\n"
"       \n"
"    image: url(:/pngicon/Resources/up_change.png);\n"
"        subcontrol-position: top;\n"
"}\n"
"QScrollBar::add-line:vertical {\n"
"        height:7px;\n"
"        background: rgb(255, 255, 255);\n"
"     \n"
"    image: url(:/pngicon/Resources/down_change.png);\n"
"        subcontrol-position: bottom;\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {\n"
"        background: rgb(170, 200, 230);\n"
"}\n"
"QScrollBar::add-line:vertical:hover {\n"
"        background: rgb(170, 200, 230);\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"        background: transparent;\n"
"}\n"
"\n"
"QScrollBar#verticalScrollBar:vertical {\n"
"        margin-top: 30px;\n"
"}\n"
"\n"
"/**********下拉列表**********/\n"
"QComboBox {\n"
"        height: 25px;\n"
"        border-radius: 4px;\n"
"        border: 1px solid rgb(111, 156, 207);\n"
"        background: white;\n"
"}\n"
"QComboBox:enabled {\n"
"        color: rgb(84, 84, 84);\n"
"}\n"
"QComboBox:!enabled {\n"
"        color: rgb(80, 80, 80);\n"
"}\n"
"QComboBox:enabled:hover, QComboBox:enabled:focus {\n"
"        color: rgb(51, 51, 51);\n"
"}\n"
"QComboBox::drop-down {\n"
"        width: 20px;\n"
"        border: none;\n"
"        background: transparent;\n"
"}\n"
"QComboBox::drop-down:hover {\n"
"        background: rgba(255, 255, 255, 30);\n"
"}\n"
"QComboBox::down-arrow {\n"
"        image: url(:/toolButton/static/down_show.png);\n"
"        border: 2px solid rgb(255, 255, 255) ; \n"
"         width:15px; \n"
"        height: 11px; \n"
"         background: #5f5f5f; \n"
"        \n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QComboBox::down-arrow:on {\n"
"        /**top: 1px;**/\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"        border: 1px solid rgb(111, 156, 207);\n"
"        background: white;\n"
"        outline: none;\n"
"}\n"
"QComboBox QAbstractItemView::item {\n"
"        height: 25px;\n"
"        color: rgb(73, 73, 73);\n"
"}\n"
"QComboBox QAbstractItemView::item:selected {\n"
"        background: rgb(232, 241, 250);\n"
"        color: rgb(2, 65, 132);\n"
"}\n"
"\n"
"/**********进度条**********/\n"
"/*QProgressBar{\n"
"        border: none;\n"
"        text-align: center;\n"
"        color: white;\n"
"        background: rgb(173, 202, 232);\n"
"}\n"
"QProgressBar::chunk {\n"
"        background: rgb(16, 135, 209);\n"
"}\n"
"\n"
"QProgressBar#progressBar {\n"
"        border: none;\n"
"        text-align: center;\n"
"        color: white;\n"
"        background-color: transparent;\n"
"        background-image: url(\":/White/progressBar\");\n"
"        background-repeat: repeat-x;\n"
"}\n"
"QProgressBar#progressBar::chunk {\n"
"        border: none;\n"
"        background-color: transparent;\n"
"        background-image: url(\":/White/progressBarChunk\");\n"
"        background-repeat: repeat-x;\n"
"}*/\n"
"\n"
"/**********复选框**********/\n"
"QCheckBox{\n"
"        font-weight: bold;\n"
"        spacing: 5px;\n"
"}\n"
"QCheckBox:enabled:checked{\n"
"        color: rgb(2, 65, 132);\n"
"}\n"
"QCheckBox:enabled:!checked{\n"
"        color: rgb(70, 71, 73);\n"
"}\n"
"QCheckBox:enabled:hover{\n"
"        color: rgb(0, 78, 161);\n"
"}\n"
"QCheckBox:!enabled{\n"
"        color: rgb(80, 80, 80);\n"
"}\n"
"QCheckBox::indicator {\n"
"        width: 15px;\n"
"        height:15px;\n"
"}\n"
"\n"
"/**********单选框**********/\n"
"QRadioButton{\n"
"        spacing: 5px;\n"
"}\n"
"QRadioButton:enabled:checked{\n"
"        color: rgb(2, 65, 132);\n"
"}\n"
"QRadioButton:enabled:!checked{\n"
"        color: rgb(70, 71, 73);\n"
"}\n"
"QRadioButton:enabled:hover{\n"
"        color: rgb(0, 78, 161);\n"
"}\n"
"QRadioButton:!enabled{\n"
"        color: rgb(80, 80, 80);\n"
"}\n"
"QRadioButton::indicator {\n"
"        width: 15px;\n"
"        height:15px;\n"
"}\n"
"\n"
"/**********输入框**********/\n"
"QLineEdit {\n"
"        border-radius: 4px;\n"
"        height: 25px;\n"
"        border: 1px solid rgb(111, 156, 207);\n"
"        background: white;\n"
"}\n"
"QLineEdit:enabled {\n"
"        color: rgb(84, 84, 84);\n"
"}\n"
"QLineEdit:enabled:hover, QLineEdit:enabled:focus {\n"
"        color: rgb(51, 51, 51);\n"
"}\n"
"QLineEdit:!enabled {\n"
"        color: rgb(80, 80, 80);\n"
"}\n"
"\n"
"/**********文本编辑框**********/\n"
"QTextEdit {\n"
"        border: 1px solid rgb(111, 156, 207);\n"
"        color: rgb(70, 71, 73);\n"
"        background: rgb(187, 212, 238);\n"
"        \n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"/**********滚动区域**********/\n"
"QScrollArea {\n"
"        border: 1px solid rgb(111, 156, 207);\n"
"        background: rgb(187, 212, 238);\n"
"}\n"
"\n"
"/**********滚动区域**********/\n"
"QWidget#transparentWidget {\n"
"        background: transparent;\n"
"}\n"
"\n"
"/**********微调器**********/\n"
"QSpinBox {\n"
"        border-radius: 4px;\n"
"        height: 24px;\n"
"        min-width: 40px;\n"
"        border: 1px solid rgb(111, 156, 207);\n"
"        background: white;\n"
"}\n"
"QSpinBox:enabled {\n"
"        color: rgb(60, 60, 60);\n"
"}\n"
"QSpinBox:enabled:hover, QSpinBox:enabled:focus {\n"
"        color: rgb(51, 51, 51);\n"
"}\n"
"QSpinBox:!enabled {\n"
"        color: rgb(210, 210, 210);\n"
"        background: transparent;\n"
"}\n"
"QSpinBox::up-button {\n"
"        border-left: 1px solid rgb(111, 156, 207);\n"
"        width: 12px;\n"
"        height: 10px;\n"
"        border-top-right-radius: 4px;\n"
"    image: url(:/toolButton/static/up_change.png);\n"
"}\n"
"QSpinBox::up-button:!enabled {\n"
"        background: transparent;\n"
"}\n"
"QSpinBox::up-button:enabled:hover {\n"
"        background: rgb(255, 255, 255, 30);\n"
"}\n"
"QSpinBox::down-button {\n"
"        border-left: 1px solid rgb(111, 156, 207);\n"
"        width: 12px;\n"
"        height:10px;\n"
"        border-bottom-right-radius: 4px;\n"
"       \n"
"    image: url(:/toolButton/static/down_change.png);\n"
"}\n"
"QSpinBox::down-button:!enabled {\n"
"        background: transparent;\n"
"}\n"
"QSpinBox::down-button:hover {\n"
"        background: rgb(255, 255, 255, 30);\n"
"}\n"
"/**********double微调器**********/\n"
"QDoubleSpinBox {\n"
"        border-radius: 4px;\n"
"        height: 24px;\n"
"        min-width: 40px;\n"
"        border: 1px solid rgb(111, 156, 207);\n"
"        background: white;\n"
"}\n"
"QDoubleSpinBox:enabled {\n"
"        color: rgb(60, 60, 60);\n"
"}\n"
"QDoubleSpinBox:enabled:hover, QSpinBox:enabled:focus {\n"
"        color: rgb(51, 51, 51);\n"
"}\n"
"QDoubleSpinBox:!enabled {\n"
"        color: rgb(210, 210, 210);\n"
"        background: transparent;\n"
"}\n"
"QDoubleSpinBox::up-button {\n"
"        border-left: 1px solid rgb(111, 156, 207);\n"
"        width: 18px;\n"
"        height: 10px;\n"
"        border-top-right-radius: 4px;\n"
"       image: url(:/pngicon/Resources/up_change.png);\n"
"}\n"
"QDoubleSpinBox::up-button:!enabled {\n"
"        background: transparent;\n"
"}\n"
"QDoubleSpinBox::up-button:enabled:hover {\n"
"        background: rgb(255, 255, 255, 30);\n"
"}\n"
"QDoubleSpinBox::down-button {\n"
"        border-left: 1px solid rgb(111, 156, 207);\n"
"        width: 18px;\n"
"        height: 10px;\n"
"        border-bottom-right-radius: 4px;\n"
"       image: url(:/pngicon/Resources/down_change.png);\n"
"}\n"
"QDoubleSpinBox::down-button:!enabled {\n"
"        background: transparent;\n"
"}\n"
"QDoubleSpinBox::down-button:hover {\n"
"        background: rgb(255, 255, 255, 30);\n"
"}\n"
"/**********标签**********/\n"
"QLabel{\n"
"    font-weight: bold;\n"
"}\n"
"QLabel#grayLabel {\n"
"        color: rgb(70, 71, 73);\n"
"}\n"
"\n"
"QLabel#highlightLabel {\n"
"        color: rgb(2, 65, 132);\n"
"}\n"
"\n"
"QLabel#redLabel {\n"
"        color: red;\n"
"}\n"
"\n"
"QLabel#grayYaHeiLabel {\n"
"        color: rgb(175, 175, 175);\n"
"        font-size: 16px;\n"
"}\n"
"\n"
"QLabel#blueLabel {\n"
"        color: rgb(0, 160, 230);\n"
"}\n"
"\n"
"QLabel#listLabel {\n"
"        color: rgb(51, 51, 51);\n"
"}\n"
"\n"
"QLabel#lineBlueLabel {\n"
"        background: rgb(0, 78, 161);\n"
"}\n"
"\n"
"QLabel#graySeperateLabel {\n"
"        background: rgb(200, 220, 230);\n"
"}\n"
"\n"
"QLabel#seperateLabel {\n"
"        background: rgb(112, 153, 194);\n"
"}\n"
"\n"
"QLabel#radiusBlueLabel {\n"
"        border-radius: 15px;\n"
"        color: white;\n"
"        font-size: 16px;\n"
"        background: rgb(0, 78, 161);\n"
"}\n"
"\n"
"QLabel#skinLabel[colorProperty=\"normal\"] {\n"
"        color: rgb(56, 99, 154);\n"
"}\n"
"QLabel#skinLabel[colorProperty=\"highlight\"] {\n"
"        color: rgb(0, 160, 230);\n"
"}\n"
"\n"
"QLabel#informationLabel {\n"
"        qproperty-pixmap: url(:/White/information);\n"
"}\n"
"\n"
"QLabel#errorLabel {\n"
"        qproperty-pixmap: url(:/White/error);\n"
"}\n"
"\n"
"QLabel#successLabel {\n"
"        qproperty-pixmap: url(:/White/success);\n"
"}\n"
"\n"
"QLabel#questionLabel {\n"
"        qproperty-pixmap: url(:/White/question);\n"
"}\n"
"\n"
"QLabel#warningLabel {\n"
"        qproperty-pixmap: url(:/White/warning);\n"
"}\n"
"\n"
"QLabel#groupLabel {\n"
"        color: rgb(56, 99, 154);\n"
"        border: 1px solid rgb(111, 156, 207);\n"
"        font-size: 15px;\n"
"        border-top-color: transparent;\n"
"        border-right-color: transparent;\n"
"        border-left-color: transparent;\n"
"}\n"
"\n"
"/**********按钮**********/\n"
"QPushButton{\n"
"        border-radius: 4px;\n"
"        border: none;\n"
"        width: 75px;\n"
"        height: 25px;\n"
"}\n"
"QPushButton:enabled {\n"
"        background: rgb(120, 170, 220);\n"
"        color: white;\n"
"}\n"
"QPushButton:!enabled {\n"
"        background: rgb(180, 180, 180);\n"
"        color: white;\n"
"}\n"
"QPushButton:enabled:hover{\n"
"        background: rgb(100, 160, 220);\n"
"}\n"
"QPushButton:enabled:pressed{\n"
"        background: rgb(0, 78, 161);\n"
"}\n"
"\n"
"QPushButton#blueButton {\n"
"        color: white;\n"
"}\n"
"QPushButton#blueButton:enabled {\n"
"        background: rgb(0, 78, 161);\n"
"        color: white;\n"
"}\n"
"QPushButton:!enabled {\n"
"        background: rgb(180, 180, 180);\n"
"        color: white;\n"
"}\n"
"QPushButton#blueButton:enabled:hover {\n"
"        background: rgb(2, 65, 132);\n"
"}\n"
"QPushButton#blueButton:enabled:pressed {\n"
"        background: rgb(6, 94, 187);\n"
"}\n"
"\n"
"QPushButton#selectButton {\n"
"        border: none;\n"
"        border-radius: none;\n"
"        border-left: 1px solid rgb(111, 156, 207);\n"
"        background: transparent;\n"
"        image: url(:/White/scan);\n"
"        color: rgb(51, 51, 51);\n"
"}\n"
"QPushButton#selectButton:enabled:hover{\n"
"        background: rgb(187, 212, 238);\n"
"}\n"
"QPushButton#selectButton:enabled:pressed{\n"
"        background: rgb(120, 170, 220);\n"
"}\n"
"\n"
"QPushButton#linkButton {\n"
"        background: transparent;\n"
"        color: rgb(0, 160, 230);\n"
"        text-align:left;\n"
"}\n"
"QPushButton#linkButton:hover {\n"
"        color: rgb(20, 185, 255);\n"
"        text-decoration: underline;\n"
"}\n"
"QPushButton#linkButton:pressed {\n"
"        color: rgb(0, 160, 230);\n"
"}\n"
"\n"
"QPushButton#transparentButton {\n"
"        background: transparent;\n"
"}\n"
"\n"
"/*****************标题栏按钮*******************/\n"
"QPushButton#minimizeButton {\n"
"        border-radius: none;\n"
"        border-bottom-left-radius: 4px;\n"
"        border-bottom-right-radius: 4px;\n"
"        background: rgb(120, 170, 220);\n"
"        image: url(:/White/minimizeHover);\n"
"}\n"
"QPushButton#minimizeButton:hover {\n"
"        image: url(:/White/minimize);\n"
"}\n"
"QPushButton#minimizeButton:pressed {\n"
"        image: url(:/White/minimizePressed);\n"
"}\n"
"\n"
"QPushButton#maximizeButton[maximizeProperty=\"maximize\"] {\n"
"        border-radius: none;\n"
"        border-bottom-left-radius: 4px;\n"
"        border-bottom-right-radius: 4px;\n"
"        background: rgb(120, 170, 220);\n"
"        image: url(:/White/maximizeHover);\n"
"}\n"
"QPushButton#maximizeButton[maximizeProperty=\"maximize\"]:hover {\n"
"        image: url(:/White/maximize);\n"
"}\n"
"QPushButton#maximizeButton[maximizeProperty=\"maximize\"]:pressed {\n"
"        image: url(:/White/maximizePressed);\n"
"}\n"
"\n"
"QPushButton#maximizeButton[maximizeProperty=\"restore\"] {\n"
"        border-radius: none;\n"
"        border-bottom-left-radius: 4px;\n"
"        border-bottom-right-radius: 4px;\n"
"        background: rgb(120, 170, 220);\n"
"        image: url(:/White/restoreHover);\n"
"}\n"
"QPushButton#maximizeButton[maximizeProperty=\"restore\"]:hover {\n"
"        image: url(:/White/restore);\n"
"}\n"
"QPushButton#maximizeButton[maximizeProperty=\"restore\"]:pressed {\n"
"        image: url(:/White/restorePressed);\n"
"}\n"
"\n"
"QPushButton#closeButton {\n"
"        border-radius: none;\n"
"        border-bottom-left-radius: 4px;\n"
"        border-bottom-right-radius: 4px;\n"
"        background: rgb(120, 170, 220);\n"
"        image: url(:/White/closeHover);\n"
"}\n"
"QPushButton#closeButton:hover {\n"
"        image: url(:/White/close);\n"
"}\n"
"QPushButton#closeButton:pressed {\n"
"        image: url(:/White/closePressed);\n"
"}\n"
"\n"
"QPushButton#skinButton {\n"
"        border-radius: none;\n"
"        border-bottom-left-radius: 4px;\n"
"        border-bottom-right-radius: 4px;\n"
"        background: rgb(120, 170, 220);\n"
"        image: url(:/White/skinHover);\n"
"}\n"
"QPushButton#skinButton:hover {\n"
"        image: url(:/White/skin);\n"
"}\n"
"QPushButton#skinButton:pressed {\n"
"        image: url(:/White/skinPressed);\n"
"}\n"
"\n"
"QPushButton#feedbackButton {\n"
"        border-radius: none;\n"
"        border-bottom-left-radius: 4px;\n"
"        border-bottom-right-radius: 4px;\n"
"        background: rgb(120, 170, 220);\n"
"        image: url(:/White/feedbackHover);\n"
"}\n"
"QPushButton#feedbackButton:hover {\n"
"        image: url(:/White/feedback);\n"
"}\n"
"QPushButton#feedbackButton:pressed {\n"
"        image: url(:/White/feedbackPressed);\n"
"}\n"
"\n"
"QPushButton#closeTipButton {\n"
"        border-radius: none;\n"
"        border-image: url(:/White/close);\n"
"        background: transparent;\n"
"}\n"
"QPushButton#closeTipButton:hover {\n"
"        border-image: url(:/White/closeHover);\n"
"}\n"
"QPushButton#closeTipButton:pressed {\n"
"        border-image: url(:/White/closePressed);\n"
"}\n"
"\n"
"QPushButton#changeSkinButton{\n"
"        border-radius: 4px;\n"
"        border: 2px solid rgb(111, 156, 207);\n"
"        background: rgb(204, 227, 252);\n"
"}\n"
"QPushButton#changeSkinButton:hover{\n"
"        border-color: rgb(60, 150, 200);\n"
"}\n"
"QPushButton#changeSkinButton:pressed, QPushButton#changeSkinButton:checked{\n"
"        border-color: rgb(0, 160, 230);\n"
"}\n"
"\n"
"QPushButton#transferButton {\n"
"        padding-left: 5px;\n"
"        padding-right: 5px;\n"
"        color: white;\n"
"        background: rgb(0, 78, 161);\n"
"}\n"
"QPushButton#transferButton:hover {\n"
"        background: rgb(2, 65, 132);\n"
"}\n"
"QPushButton#transferButton:pressed {\n"
"        background: rgb(6, 94, 187);\n"
"}\n"
"QPushButton#transferButton[iconProperty=\"left\"] {\n"
"        qproperty-icon: url(:/White/left);\n"
"}\n"
"QPushButton#transferButton[iconProperty=\"right\"] {\n"
"        qproperty-icon: url(:/White/right);\n"
"}\n"
"\n"
"QPushButton#openButton {\n"
"        border-radius: none;\n"
"        image: url(:/White/open);\n"
"        background: transparent;\n"
"}\n"
"QPushButton#openButton:hover {\n"
"        image: url(:/White/openHover);\n"
"}\n"
"QPushButton#openButton:pressed {\n"
"        image: url(:/White/openPressed);\n"
"}\n"
"\n"
"QPushButton#deleteButton {\n"
"        border-radius: none;\n"
"        image: url(:/White/delete);\n"
"        background: transparent;\n"
"}\n"
"QPushButton#deleteButton:hover {\n"
"        image: url(:/White/deleteHover);\n"
"}\n"
"QPushButton#deleteButton:pressed {\n"
"        image: url(:/White/deletePressed);\n"
"}\n"
"\n"
"QPushButton#menuButton {\n"
"        text-align: left center;\n"
"        padding-left: 3px;\n"
"        color: rgb(84, 84, 84);\n"
"        border: 1px solid rgb(111, 156, 207);\n"
"        background: white;\n"
"}\n"
"QPushButton#menuButton::menu-indicator{\n"
"        subcontrol-position: right center;\n"
"        subcontrol-origin: padding;\n"
"        image: url(:/White/arrowBottom);\n"
"        padding-right: 3px;\n"
"}\n"
"\n"
"QToolButton{\n"
"\n"
"border:none;\n"
"border-radius: 10px;\n"
"padding-top:4px;\n"
"\n"
" font:9pt \"Arial\";\n"
"    font: 75 9pt \"Adobe Caslon Pro Bold\";\n"
" }\n"
"\n"
"\n"
" QToolButton#m_toolButtonAdd{\n"
"     margin-left:5px;\n"
"     background:url(:/Resources/add.png) center no-repeat;\n"
" }\n"
"\n"
"\n"
" QToolButton#m_toolButtonAdd:hover{\n"
"background-color:\"#d4d4d4\";\n"
"\n"
" }\n"
"\n"
"\n"
" QToolButton#m_toolButtonAdd:pressed{\n"
"background-color:\"#bdbdbd\";\n"
" }\n"
"\n"
"\n"
" QToolButton#m_toolButtonAdd:disabled{\n"
"background:url(:/Resources/add_icon_disabled.png) center no-repeat;\n"
" } \n"
"\n"
"/**********按钮**********/\n"
"QToolButton#nsccButton {\n"
"        border: none;\n"
"        color: rgb(2, 65, 132);\n"
"        background: transparent;\n"
"        padding: 10px;\n"
"        qproperty-icon: url(:/White/nscc);\n"
"        qproperty-iconSize: 32px 32px;\n"
"        qproperty-toolButtonStyle: ToolButtonTextUnderIcon;\n"
"}\n"
"QToolButton#nsccButton:hover {\n"
"        background: rgb(187, 212, 238);\n"
"            \n"
"    background-color: rgb(0, 255, 255);\n"
"}\n"
"\n"
"QToolButton#transferButton {\n"
"        border: none;\n"
"        color: rgb(2, 65, 132);\n"
"        background: transparent;\n"
"        padding: 10px;\n"
"        qproperty-icon: url(:/White/transfer);\n"
"        qproperty-iconSize: 32px 32px;\n"
"        qproperty-toolButtonStyle: ToolButtonTextUnderIcon;\n"
"}\n"
"QToolButton#transferButton:hover {\n"
"        /*background: rgb(187, 212, 238);*/\n"
"    background-color: rgb(0, 255, 255);\n"
"}\n"
"QToolButton::hover {\n"
"        /*background: rgb(187, 212, 238);*/\n"
"    \n"
"    background-color: rgb(187, 212, 238);\n"
"}\n"
" QToolButton::pressed{\n"
"background-color:\"#bdbdbd\";\n"
" }")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setMinimumSize(QtCore.QSize(0, 120))
        self.tabWidget.setMaximumSize(QtCore.QSize(10000, 120))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.layoutWidget = QtWidgets.QWidget(self.tab)
        self.layoutWidget.setGeometry(QtCore.QRect(4, 0, 941, 82))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(33, 70, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 1, 9, 1, 1)
        self.toolButton_changeDir = QtWidgets.QToolButton(self.layoutWidget)
        self.toolButton_changeDir.setStyleSheet("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/toolButton/static/dir.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_changeDir.setIcon(icon)
        self.toolButton_changeDir.setIconSize(QtCore.QSize(50, 50))
        self.toolButton_changeDir.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_changeDir.setObjectName("toolButton_changeDir")
        self.gridLayout_2.addWidget(self.toolButton_changeDir, 1, 7, 1, 1)
        self.toolButton_stopGather = QtWidgets.QToolButton(self.layoutWidget)
        self.toolButton_stopGather.setStyleSheet("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/toolButton/static/stopGather.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_stopGather.setIcon(icon1)
        self.toolButton_stopGather.setIconSize(QtCore.QSize(50, 50))
        self.toolButton_stopGather.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_stopGather.setObjectName("toolButton_stopGather")
        self.gridLayout_2.addWidget(self.toolButton_stopGather, 1, 4, 1, 1)
        self.toolButton_closeCamera = QtWidgets.QToolButton(self.layoutWidget)
        self.toolButton_closeCamera.setStyleSheet("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/toolButton/static/closeCamera.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_closeCamera.setIcon(icon2)
        self.toolButton_closeCamera.setIconSize(QtCore.QSize(50, 50))
        self.toolButton_closeCamera.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_closeCamera.setObjectName("toolButton_closeCamera")
        self.gridLayout_2.addWidget(self.toolButton_closeCamera, 1, 5, 1, 1)
        self.line = QtWidgets.QFrame(self.layoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 0, 6, 2, 2)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.comboBox_cameraDeviceList = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_cameraDeviceList.setMinimumSize(QtCore.QSize(160, 23))
        self.comboBox_cameraDeviceList.setMaximumSize(QtCore.QSize(160, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_cameraDeviceList.setFont(font)
        self.comboBox_cameraDeviceList.setObjectName("comboBox_cameraDeviceList")
        self.verticalLayout_6.addWidget(self.comboBox_cameraDeviceList)
        self.checkBox_saveVideo = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_saveVideo.setMinimumSize(QtCore.QSize(72, 0))
        self.checkBox_saveVideo.setMaximumSize(QtCore.QSize(120, 16777215))
        self.checkBox_saveVideo.setStyleSheet("")
        self.checkBox_saveVideo.setObjectName("checkBox_saveVideo")
        self.verticalLayout_6.addWidget(self.checkBox_saveVideo)
        self.verticalLayout_7.addLayout(self.verticalLayout_6)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_20 = QtWidgets.QLabel(self.layoutWidget)
        self.label_20.setMinimumSize(QtCore.QSize(65, 15))
        self.label_20.setMaximumSize(QtCore.QSize(65, 15))
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_15.addWidget(self.label_20)
        self.label_gatherTime = QtWidgets.QLabel(self.layoutWidget)
        self.label_gatherTime.setMinimumSize(QtCore.QSize(70, 15))
        self.label_gatherTime.setMaximumSize(QtCore.QSize(70, 15))
        self.label_gatherTime.setSizeIncrement(QtCore.QSize(70, 15))
        self.label_gatherTime.setObjectName("label_gatherTime")
        self.horizontalLayout_15.addWidget(self.label_gatherTime)
        self.verticalLayout_7.addLayout(self.horizontalLayout_15)
        self.gridLayout_2.addLayout(self.verticalLayout_7, 0, 0, 2, 1)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_14 = QtWidgets.QLabel(self.layoutWidget)
        self.label_14.setMinimumSize(QtCore.QSize(50, 21))
        self.label_14.setMaximumSize(QtCore.QSize(50, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_6.addWidget(self.label_14)
        self.doubleSpinBox_gyrox = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.doubleSpinBox_gyrox.setMinimumSize(QtCore.QSize(42, 21))
        self.doubleSpinBox_gyrox.setMaximumSize(QtCore.QSize(80, 21))
        self.doubleSpinBox_gyrox.setReadOnly(False)
        self.doubleSpinBox_gyrox.setMinimum(-180.0)
        self.doubleSpinBox_gyrox.setMaximum(180.0)
        self.doubleSpinBox_gyrox.setSingleStep(0.01)
        self.doubleSpinBox_gyrox.setObjectName("doubleSpinBox_gyrox")
        self.horizontalLayout_6.addWidget(self.doubleSpinBox_gyrox)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_15 = QtWidgets.QLabel(self.layoutWidget)
        self.label_15.setMinimumSize(QtCore.QSize(50, 21))
        self.label_15.setMaximumSize(QtCore.QSize(50, 21))
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_9.addWidget(self.label_15)
        self.doubleSpinBox_gyroy = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.doubleSpinBox_gyroy.setMinimumSize(QtCore.QSize(42, 21))
        self.doubleSpinBox_gyroy.setMaximumSize(QtCore.QSize(80, 21))
        self.doubleSpinBox_gyroy.setMinimum(-180.0)
        self.doubleSpinBox_gyroy.setMaximum(180.0)
        self.doubleSpinBox_gyroy.setSingleStep(0.01)
        self.doubleSpinBox_gyroy.setObjectName("doubleSpinBox_gyroy")
        self.horizontalLayout_9.addWidget(self.doubleSpinBox_gyroy)
        self.verticalLayout_4.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_16 = QtWidgets.QLabel(self.layoutWidget)
        self.label_16.setMinimumSize(QtCore.QSize(50, 21))
        self.label_16.setMaximumSize(QtCore.QSize(50, 21))
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_10.addWidget(self.label_16)
        self.doubleSpinBox_gyroz = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.doubleSpinBox_gyroz.setMinimumSize(QtCore.QSize(42, 21))
        self.doubleSpinBox_gyroz.setMaximumSize(QtCore.QSize(80, 21))
        self.doubleSpinBox_gyroz.setMinimum(-180.0)
        self.doubleSpinBox_gyroz.setMaximum(180.0)
        self.doubleSpinBox_gyroz.setSingleStep(0.01)
        self.doubleSpinBox_gyroz.setObjectName("doubleSpinBox_gyroz")
        self.horizontalLayout_10.addWidget(self.doubleSpinBox_gyroz)
        self.verticalLayout_4.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_14.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSpacing(1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_17 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        self.label_17.setMinimumSize(QtCore.QSize(60, 21))
        self.label_17.setMaximumSize(QtCore.QSize(60, 21))
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_11.addWidget(self.label_17)
        self.doubleSpinBo_x = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.doubleSpinBo_x.setMinimumSize(QtCore.QSize(42, 21))
        self.doubleSpinBo_x.setMaximumSize(QtCore.QSize(80, 21))
        self.doubleSpinBo_x.setReadOnly(False)
        self.doubleSpinBo_x.setMinimum(-180.0)
        self.doubleSpinBo_x.setMaximum(180.0)
        self.doubleSpinBo_x.setSingleStep(0.01)
        self.doubleSpinBo_x.setObjectName("doubleSpinBo_x")
        self.horizontalLayout_11.addWidget(self.doubleSpinBo_x)
        self.verticalLayout_5.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_18 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_18.sizePolicy().hasHeightForWidth())
        self.label_18.setSizePolicy(sizePolicy)
        self.label_18.setMinimumSize(QtCore.QSize(60, 21))
        self.label_18.setMaximumSize(QtCore.QSize(60, 21))
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_12.addWidget(self.label_18)
        self.doubleSpinBox_y = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.doubleSpinBox_y.setMinimumSize(QtCore.QSize(42, 21))
        self.doubleSpinBox_y.setMaximumSize(QtCore.QSize(80, 21))
        self.doubleSpinBox_y.setMinimum(-180.0)
        self.doubleSpinBox_y.setMaximum(180.0)
        self.doubleSpinBox_y.setSingleStep(0.01)
        self.doubleSpinBox_y.setObjectName("doubleSpinBox_y")
        self.horizontalLayout_12.addWidget(self.doubleSpinBox_y)
        self.verticalLayout_5.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_19 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_19.sizePolicy().hasHeightForWidth())
        self.label_19.setSizePolicy(sizePolicy)
        self.label_19.setMinimumSize(QtCore.QSize(60, 21))
        self.label_19.setMaximumSize(QtCore.QSize(60, 21))
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_13.addWidget(self.label_19)
        self.doubleSpinBox_z = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.doubleSpinBox_z.setMinimumSize(QtCore.QSize(42, 21))
        self.doubleSpinBox_z.setMaximumSize(QtCore.QSize(80, 21))
        self.doubleSpinBox_z.setMinimum(-180.0)
        self.doubleSpinBox_z.setMaximum(180.0)
        self.doubleSpinBox_z.setSingleStep(0.01)
        self.doubleSpinBox_z.setObjectName("doubleSpinBox_z")
        self.horizontalLayout_13.addWidget(self.doubleSpinBox_z)
        self.verticalLayout_5.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14.addLayout(self.verticalLayout_5)
        self.gridLayout_2.addLayout(self.horizontalLayout_14, 0, 8, 2, 1)
        self.toolButton_scanCamera = QtWidgets.QToolButton(self.layoutWidget)
        self.toolButton_scanCamera.setStyleSheet("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/toolButton/static/scanCamera.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_scanCamera.setIcon(icon3)
        self.toolButton_scanCamera.setIconSize(QtCore.QSize(50, 50))
        self.toolButton_scanCamera.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_scanCamera.setObjectName("toolButton_scanCamera")
        self.gridLayout_2.addWidget(self.toolButton_scanCamera, 1, 1, 1, 1)
        self.toolButton_openCamera = QtWidgets.QToolButton(self.layoutWidget)
        self.toolButton_openCamera.setStyleSheet("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/toolButton/static/camera.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_openCamera.setIcon(icon4)
        self.toolButton_openCamera.setIconSize(QtCore.QSize(50, 50))
        self.toolButton_openCamera.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_openCamera.setObjectName("toolButton_openCamera")
        self.gridLayout_2.addWidget(self.toolButton_openCamera, 1, 2, 1, 1)
        self.toolButton_startGather = QtWidgets.QToolButton(self.layoutWidget)
        self.toolButton_startGather.setStyleSheet("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/toolButton/static/startGather.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_startGather.setIcon(icon5)
        self.toolButton_startGather.setIconSize(QtCore.QSize(50, 50))
        self.toolButton_startGather.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_startGather.setObjectName("toolButton_startGather")
        self.gridLayout_2.addWidget(self.toolButton_startGather, 1, 3, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.toolButton_datasetClip = QtWidgets.QToolButton(self.tab_2)
        self.toolButton_datasetClip.setGeometry(QtCore.QRect(123, 10, 63, 73))
        self.toolButton_datasetClip.setStyleSheet("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/toolButton/static/datasetClip.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_datasetClip.setIcon(icon6)
        self.toolButton_datasetClip.setIconSize(QtCore.QSize(50, 50))
        self.toolButton_datasetClip.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_datasetClip.setObjectName("toolButton_datasetClip")
        self.toolButton_clipVideo = QtWidgets.QToolButton(self.tab_2)
        self.toolButton_clipVideo.setGeometry(QtCore.QRect(193, 10, 63, 73))
        self.toolButton_clipVideo.setStyleSheet("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/toolButton/static/clipVideo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_clipVideo.setIcon(icon7)
        self.toolButton_clipVideo.setIconSize(QtCore.QSize(50, 50))
        self.toolButton_clipVideo.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_clipVideo.setObjectName("toolButton_clipVideo")
        self.line_3 = QtWidgets.QFrame(self.tab_2)
        self.line_3.setGeometry(QtCore.QRect(263, 1, 16, 91))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.layoutWidget1 = QtWidgets.QWidget(self.tab_2)
        self.layoutWidget1.setGeometry(QtCore.QRect(0, 0, 104, 91))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_5.setMinimumSize(QtCore.QSize(36, 0))
        self.label_5.setMaximumSize(QtCore.QSize(36, 16777215))
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.spinBox_trainRate = QtWidgets.QSpinBox(self.layoutWidget1)
        self.spinBox_trainRate.setMinimumSize(QtCore.QSize(42, 23))
        self.spinBox_trainRate.setMaximumSize(QtCore.QSize(42, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.spinBox_trainRate.setFont(font)
        self.spinBox_trainRate.setMaximum(100)
        self.spinBox_trainRate.setProperty("value", 80)
        self.spinBox_trainRate.setObjectName("spinBox_trainRate")
        self.horizontalLayout_5.addWidget(self.spinBox_trainRate)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_7.setMinimumSize(QtCore.QSize(8, 0))
        self.label_7.setMaximumSize(QtCore.QSize(8, 16777215))
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_5.addWidget(self.label_7)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_12 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_12.setMinimumSize(QtCore.QSize(36, 0))
        self.label_12.setMaximumSize(QtCore.QSize(36, 16777215))
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_3.addWidget(self.label_12)
        self.spinBox_valRate = QtWidgets.QSpinBox(self.layoutWidget1)
        self.spinBox_valRate.setMinimumSize(QtCore.QSize(42, 23))
        self.spinBox_valRate.setMaximumSize(QtCore.QSize(42, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.spinBox_valRate.setFont(font)
        self.spinBox_valRate.setMaximum(100)
        self.spinBox_valRate.setProperty("value", 10)
        self.spinBox_valRate.setObjectName("spinBox_valRate")
        self.horizontalLayout_3.addWidget(self.spinBox_valRate)
        self.label_13 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_13.setMinimumSize(QtCore.QSize(8, 0))
        self.label_13.setMaximumSize(QtCore.QSize(8, 16777215))
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_3.addWidget(self.label_13)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_8 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_8.setMinimumSize(QtCore.QSize(36, 0))
        self.label_8.setMaximumSize(QtCore.QSize(36, 16777215))
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_4.addWidget(self.label_8)
        self.spinBox_frameGap = QtWidgets.QSpinBox(self.layoutWidget1)
        self.spinBox_frameGap.setMinimumSize(QtCore.QSize(42, 23))
        self.spinBox_frameGap.setMaximumSize(QtCore.QSize(42, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.spinBox_frameGap.setFont(font)
        self.spinBox_frameGap.setMaximum(100)
        self.spinBox_frameGap.setProperty("value", 10)
        self.spinBox_frameGap.setObjectName("spinBox_frameGap")
        self.horizontalLayout_4.addWidget(self.spinBox_frameGap)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_9.setMinimumSize(QtCore.QSize(8, 0))
        self.label_9.setMaximumSize(QtCore.QSize(8, 16777215))
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_4.addWidget(self.label_9)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.toolButton_VideoAnalyse = QtWidgets.QToolButton(self.tab_2)
        self.toolButton_VideoAnalyse.setGeometry(QtCore.QRect(290, 10, 63, 73))
        self.toolButton_VideoAnalyse.setStyleSheet("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/toolButton/static/ananlyse.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_VideoAnalyse.setIcon(icon8)
        self.toolButton_VideoAnalyse.setIconSize(QtCore.QSize(50, 50))
        self.toolButton_VideoAnalyse.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_VideoAnalyse.setObjectName("toolButton_VideoAnalyse")
        self.layoutWidget_10 = QtWidgets.QWidget(self.tab_2)
        self.layoutWidget_10.setGeometry(QtCore.QRect(600, 10, 106, 67))
        self.layoutWidget_10.setObjectName("layoutWidget_10")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.layoutWidget_10)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.label_36 = QtWidgets.QLabel(self.layoutWidget_10)
        self.label_36.setMinimumSize(QtCore.QSize(60, 15))
        self.label_36.setMaximumSize(QtCore.QSize(40, 15))
        self.label_36.setObjectName("label_36")
        self.horizontalLayout_30.addWidget(self.label_36)
        self.label_maxframeCount = QtWidgets.QLabel(self.layoutWidget_10)
        self.label_maxframeCount.setMinimumSize(QtCore.QSize(35, 15))
        self.label_maxframeCount.setMaximumSize(QtCore.QSize(35, 15))
        self.label_maxframeCount.setObjectName("label_maxframeCount")
        self.horizontalLayout_30.addWidget(self.label_maxframeCount)
        self.verticalLayout_14.addLayout(self.horizontalLayout_30)
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.label_37 = QtWidgets.QLabel(self.layoutWidget_10)
        self.label_37.setMinimumSize(QtCore.QSize(60, 15))
        self.label_37.setMaximumSize(QtCore.QSize(40, 15))
        self.label_37.setObjectName("label_37")
        self.horizontalLayout_31.addWidget(self.label_37)
        self.label_minframeCount = QtWidgets.QLabel(self.layoutWidget_10)
        self.label_minframeCount.setMinimumSize(QtCore.QSize(35, 15))
        self.label_minframeCount.setMaximumSize(QtCore.QSize(35, 15))
        self.label_minframeCount.setObjectName("label_minframeCount")
        self.horizontalLayout_31.addWidget(self.label_minframeCount)
        self.verticalLayout_14.addLayout(self.horizontalLayout_31)
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.label_38 = QtWidgets.QLabel(self.layoutWidget_10)
        self.label_38.setMinimumSize(QtCore.QSize(60, 15))
        self.label_38.setMaximumSize(QtCore.QSize(40, 15))
        self.label_38.setObjectName("label_38")
        self.horizontalLayout_32.addWidget(self.label_38)
        self.label_averangeframeCount = QtWidgets.QLabel(self.layoutWidget_10)
        self.label_averangeframeCount.setMinimumSize(QtCore.QSize(35, 15))
        self.label_averangeframeCount.setMaximumSize(QtCore.QSize(35, 15))
        self.label_averangeframeCount.setObjectName("label_averangeframeCount")
        self.horizontalLayout_32.addWidget(self.label_averangeframeCount)
        self.verticalLayout_14.addLayout(self.horizontalLayout_32)
        self.layoutWidget_11 = QtWidgets.QWidget(self.tab_2)
        self.layoutWidget_11.setGeometry(QtCore.QRect(720, 10, 106, 67))
        self.layoutWidget_11.setObjectName("layoutWidget_11")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.layoutWidget_11)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        self.label_39 = QtWidgets.QLabel(self.layoutWidget_11)
        self.label_39.setMinimumSize(QtCore.QSize(60, 15))
        self.label_39.setMaximumSize(QtCore.QSize(40, 15))
        self.label_39.setObjectName("label_39")
        self.horizontalLayout_33.addWidget(self.label_39)
        self.label_maxseq = QtWidgets.QLabel(self.layoutWidget_11)
        self.label_maxseq.setMinimumSize(QtCore.QSize(35, 15))
        self.label_maxseq.setMaximumSize(QtCore.QSize(35, 15))
        self.label_maxseq.setObjectName("label_maxseq")
        self.horizontalLayout_33.addWidget(self.label_maxseq)
        self.verticalLayout_15.addLayout(self.horizontalLayout_33)
        self.horizontalLayout_34 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        self.label_40 = QtWidgets.QLabel(self.layoutWidget_11)
        self.label_40.setMinimumSize(QtCore.QSize(60, 15))
        self.label_40.setMaximumSize(QtCore.QSize(40, 15))
        self.label_40.setObjectName("label_40")
        self.horizontalLayout_34.addWidget(self.label_40)
        self.label_minseq = QtWidgets.QLabel(self.layoutWidget_11)
        self.label_minseq.setMinimumSize(QtCore.QSize(35, 15))
        self.label_minseq.setMaximumSize(QtCore.QSize(35, 15))
        self.label_minseq.setObjectName("label_minseq")
        self.horizontalLayout_34.addWidget(self.label_minseq)
        self.verticalLayout_15.addLayout(self.horizontalLayout_34)
        self.horizontalLayout_35 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_35.setObjectName("horizontalLayout_35")
        self.label_41 = QtWidgets.QLabel(self.layoutWidget_11)
        self.label_41.setMinimumSize(QtCore.QSize(60, 15))
        self.label_41.setMaximumSize(QtCore.QSize(40, 15))
        self.label_41.setObjectName("label_41")
        self.horizontalLayout_35.addWidget(self.label_41)
        self.label_averangeseq = QtWidgets.QLabel(self.layoutWidget_11)
        self.label_averangeseq.setMinimumSize(QtCore.QSize(35, 15))
        self.label_averangeseq.setMaximumSize(QtCore.QSize(35, 15))
        self.label_averangeseq.setObjectName("label_averangeseq")
        self.horizontalLayout_35.addWidget(self.label_averangeseq)
        self.verticalLayout_15.addLayout(self.horizontalLayout_35)
        self.widget = QtWidgets.QWidget(self.tab_2)
        self.widget.setGeometry(QtCore.QRect(370, 0, 106, 91))
        self.widget.setObjectName("widget")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_29 = QtWidgets.QLabel(self.widget)
        self.label_29.setMinimumSize(QtCore.QSize(60, 15))
        self.label_29.setMaximumSize(QtCore.QSize(40, 15))
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_23.addWidget(self.label_29)
        self.label_allVideos = QtWidgets.QLabel(self.widget)
        self.label_allVideos.setMinimumSize(QtCore.QSize(35, 15))
        self.label_allVideos.setMaximumSize(QtCore.QSize(35, 15))
        self.label_allVideos.setObjectName("label_allVideos")
        self.horizontalLayout_23.addWidget(self.label_allVideos)
        self.verticalLayout_12.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.label_30 = QtWidgets.QLabel(self.widget)
        self.label_30.setMinimumSize(QtCore.QSize(60, 15))
        self.label_30.setMaximumSize(QtCore.QSize(40, 15))
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_24.addWidget(self.label_30)
        self.label_trainVideos = QtWidgets.QLabel(self.widget)
        self.label_trainVideos.setMinimumSize(QtCore.QSize(35, 15))
        self.label_trainVideos.setMaximumSize(QtCore.QSize(35, 15))
        self.label_trainVideos.setObjectName("label_trainVideos")
        self.horizontalLayout_24.addWidget(self.label_trainVideos)
        self.verticalLayout_12.addLayout(self.horizontalLayout_24)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.label_31 = QtWidgets.QLabel(self.widget)
        self.label_31.setMinimumSize(QtCore.QSize(60, 15))
        self.label_31.setMaximumSize(QtCore.QSize(40, 15))
        self.label_31.setObjectName("label_31")
        self.horizontalLayout_25.addWidget(self.label_31)
        self.label_valVideos = QtWidgets.QLabel(self.widget)
        self.label_valVideos.setMinimumSize(QtCore.QSize(35, 15))
        self.label_valVideos.setMaximumSize(QtCore.QSize(35, 15))
        self.label_valVideos.setObjectName("label_valVideos")
        self.horizontalLayout_25.addWidget(self.label_valVideos)
        self.verticalLayout_12.addLayout(self.horizontalLayout_25)
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.label_32 = QtWidgets.QLabel(self.widget)
        self.label_32.setMinimumSize(QtCore.QSize(60, 15))
        self.label_32.setMaximumSize(QtCore.QSize(40, 15))
        self.label_32.setObjectName("label_32")
        self.horizontalLayout_26.addWidget(self.label_32)
        self.label_testVideos = QtWidgets.QLabel(self.widget)
        self.label_testVideos.setMinimumSize(QtCore.QSize(35, 15))
        self.label_testVideos.setMaximumSize(QtCore.QSize(35, 15))
        self.label_testVideos.setObjectName("label_testVideos")
        self.horizontalLayout_26.addWidget(self.label_testVideos)
        self.verticalLayout_12.addLayout(self.horizontalLayout_26)
        self.widget1 = QtWidgets.QWidget(self.tab_2)
        self.widget1.setGeometry(QtCore.QRect(480, 10, 106, 67))
        self.widget1.setObjectName("widget1")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.label_33 = QtWidgets.QLabel(self.widget1)
        self.label_33.setMinimumSize(QtCore.QSize(60, 15))
        self.label_33.setMaximumSize(QtCore.QSize(40, 15))
        self.label_33.setObjectName("label_33")
        self.horizontalLayout_27.addWidget(self.label_33)
        self.label_maxDuration = QtWidgets.QLabel(self.widget1)
        self.label_maxDuration.setMinimumSize(QtCore.QSize(35, 15))
        self.label_maxDuration.setMaximumSize(QtCore.QSize(35, 15))
        self.label_maxDuration.setObjectName("label_maxDuration")
        self.horizontalLayout_27.addWidget(self.label_maxDuration)
        self.verticalLayout_13.addLayout(self.horizontalLayout_27)
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.label_34 = QtWidgets.QLabel(self.widget1)
        self.label_34.setMinimumSize(QtCore.QSize(60, 15))
        self.label_34.setMaximumSize(QtCore.QSize(40, 15))
        self.label_34.setObjectName("label_34")
        self.horizontalLayout_28.addWidget(self.label_34)
        self.label_minDuration = QtWidgets.QLabel(self.widget1)
        self.label_minDuration.setMinimumSize(QtCore.QSize(35, 15))
        self.label_minDuration.setMaximumSize(QtCore.QSize(35, 15))
        self.label_minDuration.setObjectName("label_minDuration")
        self.horizontalLayout_28.addWidget(self.label_minDuration)
        self.verticalLayout_13.addLayout(self.horizontalLayout_28)
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.label_35 = QtWidgets.QLabel(self.widget1)
        self.label_35.setMinimumSize(QtCore.QSize(60, 15))
        self.label_35.setMaximumSize(QtCore.QSize(40, 15))
        self.label_35.setObjectName("label_35")
        self.horizontalLayout_29.addWidget(self.label_35)
        self.label_averangeDuration = QtWidgets.QLabel(self.widget1)
        self.label_averangeDuration.setMinimumSize(QtCore.QSize(35, 15))
        self.label_averangeDuration.setMaximumSize(QtCore.QSize(35, 15))
        self.label_averangeDuration.setObjectName("label_averangeDuration")
        self.horizontalLayout_29.addWidget(self.label_averangeDuration)
        self.verticalLayout_13.addLayout(self.horizontalLayout_29)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.layoutWidget2 = QtWidgets.QWidget(self.tab_5)
        self.layoutWidget2.setGeometry(QtCore.QRect(11, 11, 958, 75))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.toolButton_filterData = QtWidgets.QToolButton(self.layoutWidget2)
        self.toolButton_filterData.setStyleSheet("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/toolButton/static/deleteImg.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_filterData.setIcon(icon9)
        self.toolButton_filterData.setIconSize(QtCore.QSize(50, 50))
        self.toolButton_filterData.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_filterData.setObjectName("toolButton_filterData")
        self.horizontalLayout_19.addWidget(self.toolButton_filterData)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_21 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_21.setMinimumSize(QtCore.QSize(40, 15))
        self.label_21.setMaximumSize(QtCore.QSize(40, 15))
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_16.addWidget(self.label_21)
        self.label_imageCountAll = QtWidgets.QLabel(self.layoutWidget2)
        self.label_imageCountAll.setMinimumSize(QtCore.QSize(35, 15))
        self.label_imageCountAll.setMaximumSize(QtCore.QSize(35, 15))
        self.label_imageCountAll.setObjectName("label_imageCountAll")
        self.horizontalLayout_16.addWidget(self.label_imageCountAll)
        self.verticalLayout_10.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_23 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_23.setMinimumSize(QtCore.QSize(40, 15))
        self.label_23.setMaximumSize(QtCore.QSize(40, 15))
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_17.addWidget(self.label_23)
        self.label_imageDeleteCount = QtWidgets.QLabel(self.layoutWidget2)
        self.label_imageDeleteCount.setMinimumSize(QtCore.QSize(35, 15))
        self.label_imageDeleteCount.setMaximumSize(QtCore.QSize(35, 15))
        self.label_imageDeleteCount.setObjectName("label_imageDeleteCount")
        self.horizontalLayout_17.addWidget(self.label_imageDeleteCount)
        self.verticalLayout_10.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_25 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_25.setMinimumSize(QtCore.QSize(40, 15))
        self.label_25.setMaximumSize(QtCore.QSize(40, 15))
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_18.addWidget(self.label_25)
        self.label_imageSurplusCount = QtWidgets.QLabel(self.layoutWidget2)
        self.label_imageSurplusCount.setMinimumSize(QtCore.QSize(35, 15))
        self.label_imageSurplusCount.setMaximumSize(QtCore.QSize(35, 15))
        self.label_imageSurplusCount.setObjectName("label_imageSurplusCount")
        self.horizontalLayout_18.addWidget(self.label_imageSurplusCount)
        self.verticalLayout_10.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_19.addLayout(self.verticalLayout_10)
        self.toolButton_generateAnnotation = QtWidgets.QToolButton(self.layoutWidget2)
        self.toolButton_generateAnnotation.setStyleSheet("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/toolButton/static/generateAnnotaton.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_generateAnnotation.setIcon(icon10)
        self.toolButton_generateAnnotation.setIconSize(QtCore.QSize(50, 50))
        self.toolButton_generateAnnotation.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_generateAnnotation.setObjectName("toolButton_generateAnnotation")
        self.horizontalLayout_19.addWidget(self.toolButton_generateAnnotation)
        self.toolButton_checkFromJson = QtWidgets.QToolButton(self.layoutWidget2)
        self.toolButton_checkFromJson.setStyleSheet("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/toolButton/static/json.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_checkFromJson.setIcon(icon11)
        self.toolButton_checkFromJson.setIconSize(QtCore.QSize(50, 50))
        self.toolButton_checkFromJson.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_checkFromJson.setObjectName("toolButton_checkFromJson")
        self.horizontalLayout_19.addWidget(self.toolButton_checkFromJson)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_22 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_22.setMinimumSize(QtCore.QSize(72, 15))
        self.label_22.setMaximumSize(QtCore.QSize(72, 15))
        self.label_22.setObjectName("label_22")
        self.verticalLayout_8.addWidget(self.label_22)
        self.comboBox_labelList = QtWidgets.QComboBox(self.layoutWidget2)
        self.comboBox_labelList.setMinimumSize(QtCore.QSize(0, 23))
        self.comboBox_labelList.setMaximumSize(QtCore.QSize(16777215, 23))
        self.comboBox_labelList.setObjectName("comboBox_labelList")
        self.verticalLayout_8.addWidget(self.comboBox_labelList)
        self.verticalLayout_9.addLayout(self.verticalLayout_8)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_numofClasses = QtWidgets.QLabel(self.layoutWidget2)
        self.label_numofClasses.setMinimumSize(QtCore.QSize(30, 15))
        self.label_numofClasses.setMaximumSize(QtCore.QSize(50, 15))
        self.label_numofClasses.setSizeIncrement(QtCore.QSize(50, 15))
        self.label_numofClasses.setObjectName("label_numofClasses")
        self.horizontalLayout_8.addWidget(self.label_numofClasses)
        self.label_24 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_24.setMaximumSize(QtCore.QSize(55, 15))
        self.label_24.setSizeIncrement(QtCore.QSize(55, 15))
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_8.addWidget(self.label_24)
        self.verticalLayout_9.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_19.addLayout(self.verticalLayout_9)
        self.toolButton_jsonToTxt = QtWidgets.QToolButton(self.layoutWidget2)
        self.toolButton_jsonToTxt.setStyleSheet("")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/toolButton/static/jsontotxt.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_jsonToTxt.setIcon(icon12)
        self.toolButton_jsonToTxt.setIconSize(QtCore.QSize(50, 50))
        self.toolButton_jsonToTxt.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_jsonToTxt.setObjectName("toolButton_jsonToTxt")
        self.horizontalLayout_19.addWidget(self.toolButton_jsonToTxt)
        self.toolButton_checkFromTxt = QtWidgets.QToolButton(self.layoutWidget2)
        self.toolButton_checkFromTxt.setStyleSheet("")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/toolButton/static/txt.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_checkFromTxt.setIcon(icon13)
        self.toolButton_checkFromTxt.setIconSize(QtCore.QSize(50, 50))
        self.toolButton_checkFromTxt.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_checkFromTxt.setObjectName("toolButton_checkFromTxt")
        self.horizontalLayout_19.addWidget(self.toolButton_checkFromTxt)
        self.toolButton_checkLastImg = QtWidgets.QToolButton(self.layoutWidget2)
        self.toolButton_checkLastImg.setStyleSheet("")
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/toolButton/static/last.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_checkLastImg.setIcon(icon14)
        self.toolButton_checkLastImg.setIconSize(QtCore.QSize(50, 50))
        self.toolButton_checkLastImg.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_checkLastImg.setObjectName("toolButton_checkLastImg")
        self.horizontalLayout_19.addWidget(self.toolButton_checkLastImg)
        self.toolButton_checkNextImg = QtWidgets.QToolButton(self.layoutWidget2)
        self.toolButton_checkNextImg.setStyleSheet("")
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/toolButton/static/next.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_checkNextImg.setIcon(icon15)
        self.toolButton_checkNextImg.setIconSize(QtCore.QSize(50, 50))
        self.toolButton_checkNextImg.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_checkNextImg.setObjectName("toolButton_checkNextImg")
        self.horizontalLayout_19.addWidget(self.toolButton_checkNextImg)
        self.toolButton_generateImgList = QtWidgets.QToolButton(self.layoutWidget2)
        self.toolButton_generateImgList.setStyleSheet("")
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(":/toolButton/static/generateImgList.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_generateImgList.setIcon(icon16)
        self.toolButton_generateImgList.setIconSize(QtCore.QSize(50, 50))
        self.toolButton_generateImgList.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_generateImgList.setObjectName("toolButton_generateImgList")
        self.horizontalLayout_19.addWidget(self.toolButton_generateImgList)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.spinBox_allcheck = QtWidgets.QSpinBox(self.layoutWidget2)
        self.spinBox_allcheck.setMinimumSize(QtCore.QSize(42, 0))
        self.spinBox_allcheck.setMaximumSize(QtCore.QSize(35, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.spinBox_allcheck.setFont(font)
        self.spinBox_allcheck.setObjectName("spinBox_allcheck")
        self.horizontalLayout_2.addWidget(self.spinBox_allcheck)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget2)
        self.label.setMinimumSize(QtCore.QSize(16, 0))
        self.label.setMaximumSize(QtCore.QSize(16, 16777215))
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.label_checkImgIndex = QtWidgets.QLabel(self.layoutWidget2)
        self.label_checkImgIndex.setMinimumSize(QtCore.QSize(16, 0))
        self.label_checkImgIndex.setMaximumSize(QtCore.QSize(16, 16777215))
        self.label_checkImgIndex.setObjectName("label_checkImgIndex")
        self.horizontalLayout.addWidget(self.label_checkImgIndex)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_3.setMinimumSize(QtCore.QSize(16, 0))
        self.label_3.setMaximumSize(QtCore.QSize(16, 16777215))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_4.setMinimumSize(QtCore.QSize(20, 0))
        self.label_4.setMaximumSize(QtCore.QSize(20, 16777215))
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.label_num_of_allcheck = QtWidgets.QLabel(self.layoutWidget2)
        self.label_num_of_allcheck.setMinimumSize(QtCore.QSize(16, 0))
        self.label_num_of_allcheck.setMaximumSize(QtCore.QSize(16, 16777215))
        self.label_num_of_allcheck.setObjectName("label_num_of_allcheck")
        self.horizontalLayout.addWidget(self.label_num_of_allcheck)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_6.setMinimumSize(QtCore.QSize(16, 0))
        self.label_6.setMaximumSize(QtCore.QSize(16, 16777215))
        self.label_6.setObjectName("label_6")
        self.horizontalLayout.addWidget(self.label_6)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_19.addLayout(self.verticalLayout_2)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem2)
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.toolButton_generatePico = QtWidgets.QToolButton(self.tab_4)
        self.toolButton_generatePico.setGeometry(QtCore.QRect(200, 0, 63, 73))
        self.toolButton_generatePico.setStyleSheet("")
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(":/toolButton/static/roi.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_generatePico.setIcon(icon17)
        self.toolButton_generatePico.setIconSize(QtCore.QSize(50, 50))
        self.toolButton_generatePico.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_generatePico.setObjectName("toolButton_generatePico")
        self.toolButton_transToCOCO = QtWidgets.QToolButton(self.tab_4)
        self.toolButton_transToCOCO.setGeometry(QtCore.QRect(540, 0, 63, 73))
        self.toolButton_transToCOCO.setStyleSheet("")
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(":/toolButton/static/transcoco.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_transToCOCO.setIcon(icon18)
        self.toolButton_transToCOCO.setIconSize(QtCore.QSize(50, 50))
        self.toolButton_transToCOCO.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_transToCOCO.setObjectName("toolButton_transToCOCO")
        self.layoutWidget3 = QtWidgets.QWidget(self.tab_4)
        self.layoutWidget3.setGeometry(QtCore.QRect(20, 20, 173, 28))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_10 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_10.setMinimumSize(QtCore.QSize(81, 0))
        self.label_10.setMaximumSize(QtCore.QSize(81, 16777215))
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_7.addWidget(self.label_10)
        self.spinBox_picodata_num = QtWidgets.QSpinBox(self.layoutWidget3)
        self.spinBox_picodata_num.setProperty("value", 10)
        self.spinBox_picodata_num.setObjectName("spinBox_picodata_num")
        self.horizontalLayout_7.addWidget(self.spinBox_picodata_num)
        self.label_11 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_11.setMinimumSize(QtCore.QSize(21, 0))
        self.label_11.setMaximumSize(QtCore.QSize(21, 16777215))
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_7.addWidget(self.label_11)
        self.toolButton_picodatafilter = QtWidgets.QToolButton(self.tab_4)
        self.toolButton_picodatafilter.setGeometry(QtCore.QRect(290, 10, 63, 73))
        self.toolButton_picodatafilter.setStyleSheet("")
        self.toolButton_picodatafilter.setIcon(icon9)
        self.toolButton_picodatafilter.setIconSize(QtCore.QSize(50, 50))
        self.toolButton_picodatafilter.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_picodatafilter.setObjectName("toolButton_picodatafilter")
        self.layoutWidget_2 = QtWidgets.QWidget(self.tab_4)
        self.layoutWidget_2.setGeometry(QtCore.QRect(430, 10, 86, 67))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_26 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_26.setMinimumSize(QtCore.QSize(40, 15))
        self.label_26.setMaximumSize(QtCore.QSize(40, 15))
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_20.addWidget(self.label_26)
        self.label_PICOimageCountAll = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_PICOimageCountAll.setMinimumSize(QtCore.QSize(35, 15))
        self.label_PICOimageCountAll.setMaximumSize(QtCore.QSize(35, 15))
        self.label_PICOimageCountAll.setObjectName("label_PICOimageCountAll")
        self.horizontalLayout_20.addWidget(self.label_PICOimageCountAll)
        self.verticalLayout_11.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_27 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_27.setMinimumSize(QtCore.QSize(40, 15))
        self.label_27.setMaximumSize(QtCore.QSize(40, 15))
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_21.addWidget(self.label_27)
        self.label_PICOimageDeleteCount = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_PICOimageDeleteCount.setMinimumSize(QtCore.QSize(35, 15))
        self.label_PICOimageDeleteCount.setMaximumSize(QtCore.QSize(35, 15))
        self.label_PICOimageDeleteCount.setObjectName("label_PICOimageDeleteCount")
        self.horizontalLayout_21.addWidget(self.label_PICOimageDeleteCount)
        self.verticalLayout_11.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_28 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_28.setMinimumSize(QtCore.QSize(40, 15))
        self.label_28.setMaximumSize(QtCore.QSize(40, 15))
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_22.addWidget(self.label_28)
        self.label_PICOimageSurplusCount = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_PICOimageSurplusCount.setMinimumSize(QtCore.QSize(35, 15))
        self.label_PICOimageSurplusCount.setMaximumSize(QtCore.QSize(35, 15))
        self.label_PICOimageSurplusCount.setObjectName("label_PICOimageSurplusCount")
        self.horizontalLayout_22.addWidget(self.label_PICOimageSurplusCount)
        self.verticalLayout_11.addLayout(self.horizontalLayout_22)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.toolButton_startTest = QtWidgets.QToolButton(self.tab_3)
        self.toolButton_startTest.setGeometry(QtCore.QRect(40, 10, 63, 73))
        self.toolButton_startTest.setStyleSheet("")
        self.toolButton_startTest.setIcon(icon7)
        self.toolButton_startTest.setIconSize(QtCore.QSize(50, 50))
        self.toolButton_startTest.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_startTest.setObjectName("toolButton_startTest")
        self.toolButton_stopTest = QtWidgets.QToolButton(self.tab_3)
        self.toolButton_stopTest.setGeometry(QtCore.QRect(120, 10, 63, 73))
        self.toolButton_stopTest.setStyleSheet("")
        self.toolButton_stopTest.setIcon(icon7)
        self.toolButton_stopTest.setIconSize(QtCore.QSize(50, 50))
        self.toolButton_stopTest.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_stopTest.setObjectName("toolButton_stopTest")
        self.tabWidget.addTab(self.tab_3, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.label_imgShow = QtWidgets.QLabel(self.centralwidget)
        self.label_imgShow.setMinimumSize(QtCore.QSize(920, 500))
        self.label_imgShow.setStyleSheet("background-color: rgb(235, 253, 255);\n"
"color: rgb(170, 255, 255);")
        self.label_imgShow.setObjectName("label_imgShow")
        self.verticalLayout.addWidget(self.label_imgShow)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1013, 33))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpenFile = QtWidgets.QAction(MainWindow)
        self.actionOpenFile.setObjectName("actionOpenFile")
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.menuFile.addAction(self.actionOpenFile)
        self.menuFile.addAction(self.actionClose)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.toolButton_changeDir.setText(_translate("MainWindow", "更改目录"))
        self.toolButton_stopGather.setText(_translate("MainWindow", "停止采集"))
        self.toolButton_closeCamera.setText(_translate("MainWindow", "关闭相机"))
        self.checkBox_saveVideo.setText(_translate("MainWindow", "保存视频"))
        self.label_20.setText(_translate("MainWindow", "记录时长："))
        self.label_gatherTime.setText(_translate("MainWindow", "0.0"))
        self.label_14.setText(_translate("MainWindow", "gyro_x:"))
        self.label_15.setText(_translate("MainWindow", "gyro_y:"))
        self.label_16.setText(_translate("MainWindow", "gyrozx:"))
        self.label_17.setText(_translate("MainWindow", "Euler_x:"))
        self.label_18.setText(_translate("MainWindow", "Euler_y:"))
        self.label_19.setText(_translate("MainWindow", "Euler_z:"))
        self.toolButton_scanCamera.setText(_translate("MainWindow", "扫描相机"))
        self.toolButton_openCamera.setText(_translate("MainWindow", "打开相机"))
        self.toolButton_startGather.setText(_translate("MainWindow", "开始采集"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "视频采集"))
        self.toolButton_datasetClip.setText(_translate("MainWindow", "数据分割"))
        self.toolButton_clipVideo.setText(_translate("MainWindow", "间隔抽帧"))
        self.label_5.setText(_translate("MainWindow", "Train:"))
        self.label_7.setText(_translate("MainWindow", "%"))
        self.label_12.setText(_translate("MainWindow", "Val:"))
        self.label_13.setText(_translate("MainWindow", "%"))
        self.label_8.setText(_translate("MainWindow", "F Gap:"))
        self.label_9.setText(_translate("MainWindow", "f"))
        self.toolButton_VideoAnalyse.setText(_translate("MainWindow", "视频分析"))
        self.label_36.setText(_translate("MainWindow", "最大帧数："))
        self.label_maxframeCount.setText(_translate("MainWindow", "0"))
        self.label_37.setText(_translate("MainWindow", "最小帧数："))
        self.label_minframeCount.setText(_translate("MainWindow", "0"))
        self.label_38.setText(_translate("MainWindow", "平均帧数："))
        self.label_averangeframeCount.setText(_translate("MainWindow", "0"))
        self.label_39.setText(_translate("MainWindow", "最大序列："))
        self.label_maxseq.setText(_translate("MainWindow", "0"))
        self.label_40.setText(_translate("MainWindow", "最小序列："))
        self.label_minseq.setText(_translate("MainWindow", "0"))
        self.label_41.setText(_translate("MainWindow", "平均序列："))
        self.label_averangeseq.setText(_translate("MainWindow", "0"))
        self.label_29.setText(_translate("MainWindow", "视频总数："))
        self.label_allVideos.setText(_translate("MainWindow", "0"))
        self.label_30.setText(_translate("MainWindow", "训练集："))
        self.label_trainVideos.setText(_translate("MainWindow", "0"))
        self.label_31.setText(_translate("MainWindow", "验证集："))
        self.label_valVideos.setText(_translate("MainWindow", "0"))
        self.label_32.setText(_translate("MainWindow", "测试集："))
        self.label_testVideos.setText(_translate("MainWindow", "0"))
        self.label_33.setText(_translate("MainWindow", "最大时长："))
        self.label_maxDuration.setText(_translate("MainWindow", "0"))
        self.label_34.setText(_translate("MainWindow", "最小时长："))
        self.label_minDuration.setText(_translate("MainWindow", "0"))
        self.label_35.setText(_translate("MainWindow", "平均时长："))
        self.label_averangeDuration.setText(_translate("MainWindow", "0"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "视频处理"))
        self.toolButton_filterData.setText(_translate("MainWindow", "过滤数据"))
        self.label_21.setText(_translate("MainWindow", "总计："))
        self.label_imageCountAll.setText(_translate("MainWindow", "0"))
        self.label_23.setText(_translate("MainWindow", "删除："))
        self.label_imageDeleteCount.setText(_translate("MainWindow", "0"))
        self.label_25.setText(_translate("MainWindow", "剩余："))
        self.label_imageSurplusCount.setText(_translate("MainWindow", "0"))
        self.toolButton_generateAnnotation.setText(_translate("MainWindow", "生成标注"))
        self.toolButton_checkFromJson.setText(_translate("MainWindow", "Json验证"))
        self.label_22.setText(_translate("MainWindow", "LabelList:"))
        self.label_numofClasses.setText(_translate("MainWindow", "0"))
        self.label_24.setText(_translate("MainWindow", "Classes"))
        self.toolButton_jsonToTxt.setText(_translate("MainWindow", "JsonToTxt"))
        self.toolButton_checkFromTxt.setText(_translate("MainWindow", "TXT验证"))
        self.toolButton_checkLastImg.setText(_translate("MainWindow", "显示上张"))
        self.toolButton_checkNextImg.setText(_translate("MainWindow", "显示下张"))
        self.toolButton_generateImgList.setText(_translate("MainWindow", "生成列表"))
        self.label_2.setText(_translate("MainWindow", "校验数目："))
        self.label.setText(_translate("MainWindow", "第"))
        self.label_checkImgIndex.setText(_translate("MainWindow", "0"))
        self.label_3.setText(_translate("MainWindow", "张"))
        self.label_4.setText(_translate("MainWindow", "/共"))
        self.label_num_of_allcheck.setText(_translate("MainWindow", "0"))
        self.label_6.setText(_translate("MainWindow", "张"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "labelme后处理"))
        self.toolButton_generatePico.setText(_translate("MainWindow", "截取图像"))
        self.toolButton_transToCOCO.setText(_translate("MainWindow", "coco转换"))
        self.label_10.setText(_translate("MainWindow", "每个视频抽取"))
        self.label_11.setText(_translate("MainWindow", "帧"))
        self.toolButton_picodatafilter.setText(_translate("MainWindow", "数据过滤"))
        self.label_26.setText(_translate("MainWindow", "总计："))
        self.label_PICOimageCountAll.setText(_translate("MainWindow", "0"))
        self.label_27.setText(_translate("MainWindow", "删除："))
        self.label_PICOimageDeleteCount.setText(_translate("MainWindow", "0"))
        self.label_28.setText(_translate("MainWindow", "剩余："))
        self.label_PICOimageSurplusCount.setText(_translate("MainWindow", "0"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "pico"))
        self.toolButton_startTest.setText(_translate("MainWindow", "开始实验"))
        self.toolButton_stopTest.setText(_translate("MainWindow", "结束实验"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "采集实验"))
        self.label_imgShow.setText(_translate("MainWindow", "DisplayArea"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionOpenFile.setText(_translate("MainWindow", "Open"))
        self.actionClose.setText(_translate("MainWindow", "Close"))
import toolButtonIcon_rc
