# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindowGUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1063, 754)
        MainWindow.setStyleSheet("/*\n"
"* Description : 白色靓丽\n"
"*/\n"
"\n"
"/**********子界面背景**********/\n"
"/*QWidget#customWidget {\n"
"        background: rgb(173, 202, 232);\n"
"}\n"
"\n"
"/**********子界面中央背景**********/\n"
"/*QWidget#centerWidget {\n"
"        background: rgb(232, 241, 252);\n"
"}\n"
"\n"
"/**********主界面样式**********/\n"
"/*QWidget#mainWindow_dockWidget {\n"
"        border: 1px solid rgb(111, 156, 207);\n"
"        \n"
"    background: rgb(232, 241, 252);\n"
"}\n"
"\n"
"QWidget#messageWidget {\n"
"        background: rgba(173, 202, 232, 50%);\n"
"}\n"
"\n"
"QWidget#loadingWidget {\n"
"        border: none;\n"
"        border-radius: 5px;\n"
"        background: rgb(187, 212, 238);\n"
"\n"
"}\n"
"\n"
"QWidget#remoteWidget {\n"
"        border-top-right-radius: 10px;\n"
"        border-bottom-right-radius: 10px;\n"
"        border: 1px solid rgb(111, 156, 207);\n"
"        border-left: none;\n"
"        background: transparent;\n"
"}*/\n"
"\n"
"StyledWidget {\n"
"        qproperty-normalColor: rgb(65, 65, 65);\n"
"        qproperty-disableColor: rgb(180, 180, 180);\n"
"        qproperty-highlightColor: rgb(0, 160, 230);\n"
"        qproperty-errorColor: red;\n"
"}\n"
"\n"
"QProgressIndicator {\n"
"        qproperty-color: rgb(2, 65, 132);\n"
"}\n"
"\n"
"/**********提示**********/\n"
"QToolTip{\n"
"        border: 1px solid rgb(111, 156, 207);\n"
"        background: white;\n"
"        color: rgb(51, 51, 51);\n"
"}\n"
"\n"
"/**********菜单栏**********/\n"
"QMenuBar {\n"
"        background: rgb(187, 212, 238);\n"
"        border: 1px solid rgb(111, 156, 207);\n"
"        border-left: none;\n"
"        border-right: none;\n"
"}\n"
"QMenuBar::item {\n"
"        border: 1px solid transparent;\n"
"        padding: 5px 10px 5px 10px;\n"
"        background: transparent;\n"
"}\n"
"QMenuBar::item:enabled {\n"
"        color: rgb(2, 65, 132);\n"
"}\n"
"QMenuBar::item:!enabled {\n"
"        color: rgb(155, 155, 155);\n"
"}\n"
"QMenuBar::item:enabled:selected {\n"
"        border-top-color: rgb(111, 156, 207);\n"
"        border-bottom-color: rgb(111, 156, 207);\n"
"        background: rgb(198, 224, 252);\n"
"}\n"
"\n"
"/**********菜单**********/\n"
"QMenu {\n"
"        border: 1px solid rgb(111, 156, 207);\n"
"        background: rgb(232, 241, 250);\n"
"}\n"
"QMenu::item {\n"
"        height: 22px;\n"
"        padding: 0px 25px 0px 20px;\n"
"}\n"
"QMenu::item:enabled {\n"
"        color: rgb(84, 84, 84);\n"
"}\n"
"QMenu::item:!enabled {\n"
"        color: rgb(155, 155, 155);\n"
"}\n"
"QMenu::item:enabled:selected {\n"
"        color: rgb(2, 65, 132);\n"
"        background: rgba(255, 255, 255, 200);\n"
"}\n"
"QMenu::separator {\n"
"        height: 1px;\n"
"        background: rgb(111, 156, 207);\n"
"}\n"
"QMenu::indicator {\n"
"        width: 13px;\n"
"        height: 13px;\n"
"}\n"
"QMenu::icon {\n"
"        padding-left: 2px;\n"
"        padding-right: 2px;\n"
"}\n"
"\n"
"/**********状态栏**********/\n"
"QStatusBar {\n"
"        background: rgb(187, 212, 238);\n"
"        border: 1px solid rgb(111, 156, 207);\n"
"        border-left: none;\n"
"        border-right: none;\n"
"        border-bottom: none;\n"
"}\n"
"QStatusBar::item {\n"
"    border: none;\n"
"    border-right: 1px solid rgb(111, 156, 207);\n"
"}\n"
"\n"
"/**********分组框**********/\n"
"QGroupBox {\n"
"        font-size: 15px;\n"
"        border: 1px solid rgb(111, 156, 207);\n"
"        border-radius: 4px;\n"
"        margin-top: 13px;\n"
"}\n"
"QGroupBox::title {\n"
"        color: rgb(56, 99, 154);\n"
"        top: -12px;\n"
"        left: 10px;\n"
"}\n"
"\n"
"/**********页签项**********/\n"
"QTabWidget::pane {\n"
"        border: none;\n"
"        border-top: 3px solid rgb(0, 78, 161);\n"
"        background: rgb(187, 212, 238);\n"
"}\n"
"QTabWidget::tab-bar {\n"
"        border: none;\n"
"}\n"
"QTabBar::tab {\n"
"        border: none;\n"
"        border-top-left-radius: 1px;\n"
"        border-top-right-radius: 1px;\n"
"        color: white;\n"
"        background: rgb(120, 170, 220);\n"
"        height: 28px;\n"
"        min-width: 85px;\n"
"        \n"
"}\n"
"QTabBar::tab:hover {\n"
"        background: rgb(0, 78, 161);\n"
"}\n"
"QTabBar::tab:selected {\n"
"        color: white;\n"
"        background: rgb(0, 78, 161);\n"
"}\n"
"\n"
"QTabWidget#tabWidget::pane {\n"
"        border: 1px solid rgb(111, 156, 207);\n"
"        background: rgb(232, 241, 252);\n"
"        margin-top: -1px;\n"
"}\n"
"\n"
"QTabBar#tabBar::tab {\n"
"        border: 1px solid rgb(111, 156, 207);\n"
"        border-bottom: none;\n"
"        color: rgb(70, 71, 73);\n"
"        background: transparent;\n"
"}\n"
"QTabBar#tabBar::tab:hover {\n"
"        color: rgb(2, 65, 132);\n"
"}\n"
"QTabBar#tabBar::tab:selected {\n"
"        color: rgb(2, 65, 132);\n"
"        background: rgb(232, 241, 252);\n"
"}\n"
"\n"
"/**********表头**********/\n"
"QHeaderView{\n"
"        border: none;\n"
"        border-bottom: 3px solid rgb(0, 78, 161);\n"
"        background: transparent;\n"
"        min-height: 30px;\n"
"}\n"
"QHeaderView::section:horizontal {\n"
"        border: none;\n"
"        color: rgb(2, 65, 132);\n"
"        background: transparent;\n"
"        padding-left: 5px;\n"
"}\n"
"QHeaderView::section:horizontal:hover {\n"
"        color: white;\n"
"        background: rgb(0, 78, 161);\n"
"}\n"
"QHeaderView::section:horizontal:pressed {\n"
"        color: white;\n"
"        background: rgb(6, 94, 187);\n"
"}\n"
"QHeaderView::up-arrow {\n"
"        width: 13px;\n"
"        height: 11px;\n"
"        padding-right: 5px;\n"
"        image: url(:/White/topArrow);\n"
"        subcontrol-position: center right;\n"
"}\n"
"QHeaderView::up-arrow:hover, QHeaderView::up-arrow:pressed {\n"
"        image: url(:/White/topArrowHover);\n"
"}\n"
"QHeaderView::down-arrow {\n"
"        width: 13px;\n"
"        height: 11px;\n"
"        padding-right: 5px;\n"
"        image: url(:/White/bottomArrow);\n"
"        subcontrol-position: center right;\n"
"}\n"
"QHeaderView::down-arrow:hover, QHeaderView::down-arrow:pressed {\n"
"        image: url(:/White/bottomArrowHover);\n"
"}\n"
"\n"
"/**********表格**********/\n"
"QTableView {\n"
"        border: 1px solid rgb(111, 156, 207);\n"
"        background: rgb(224, 238, 255);\n"
"        gridline-color: rgb(111, 156, 207);\n"
"}\n"
"QTableView::item {\n"
"        padding-left: 5px;\n"
"        padding-right: 5px;\n"
"        border: none;\n"
"        background: white;\n"
"        border-right: 1px solid rgb(111, 156, 207);\n"
"        border-bottom: 1px solid rgb(111, 156, 207);\n"
"}\n"
"QTableView::item:selected {\n"
"        background: rgba(255, 255, 255, 100);\n"
"}\n"
"QTableView::item:selected:!active {\n"
"        color: rgb(65, 65, 65);\n"
"}\n"
"QTableView::indicator {\n"
"        width: 20px;\n"
"        height: 20px;\n"
"}\n"
"QTableView::indicator:enabled:unchecked {\n"
"        image: url(:/White/checkBox);\n"
"}\n"
"QTableView::indicator:enabled:unchecked:hover {\n"
"        image: url(:/White/checkBoxHover);\n"
"}\n"
"QTableView::indicator:enabled:unchecked:pressed {\n"
"        image: url(:/White/checkBoxPressed);\n"
"}\n"
"QTableView::indicator:enabled:checked {\n"
"        image: url(:/White/checkBoxChecked);\n"
"}\n"
"QTableView::indicator:enabled:checked:hover {\n"
"        image: url(:/White/checkBoxCheckedHover);\n"
"}\n"
"QTableView::indicator:enabled:checked:pressed {\n"
"        image: url(:/White/checkBoxCheckedPressed);\n"
"}\n"
"QTableView::indicator:enabled:indeterminate {\n"
"        image: url(:/White/checkBoxIndeterminate);\n"
"}\n"
"QTableView::indicator:enabled:indeterminate:hover {\n"
"        image: url(:/White/checkBoxIndeterminateHover);\n"
"}\n"
"QTableView::indicator:enabled:indeterminate:pressed {\n"
"        image: url(:/White/checkBoxIndeterminatePressed);\n"
"}\n"
"\n"
"/**********滚动条-水平**********/\n"
"QScrollBar:horizontal {\n"
"        height: 20px;\n"
"        background: transparent;\n"
"        margin-top: 3px;\n"
"        margin-bottom: 3px;\n"
"}\n"
"QScrollBar::handle:horizontal {\n"
"        height: 20px;\n"
"        min-width: 30px;\n"
"        background: rgb(170, 200, 230);\n"
"        margin-left: 15px;\n"
"        margin-right: 15px;\n"
"}\n"
"QScrollBar::handle:horizontal:hover {\n"
"        background: rgb(165, 195, 225);\n"
"}\n"
"QScrollBar::sub-line:horizontal {\n"
"        width: 12px;\n"
"        background: transparent;\n"
"    image: url(:/pngicon/Resources/left_change.png);\n"
"        subcontrol-position: left;\n"
"}\n"
"QScrollBar::add-line:horizontal {\n"
"        width: 12px;\n"
"        background: transparent;\n"
"        \n"
"    image: url(:/pngicon/Resources/right_change.png);\n"
"        subcontrol-position: right;\n"
"}\n"
"QScrollBar::sub-line:horizontal:hover {\n"
"        background: rgb(170, 200, 230);\n"
"}\n"
"QScrollBar::add-line:horizontal:hover {\n"
"        background: rgb(170, 200, 230);\n"
"}\n"
"QScrollBar::add-page:horizontal,QScrollBar::sub-page:horizontal {\n"
"        background: transparent;\n"
"}\n"
"\n"
"/**********滚动条-垂直**********/\n"
"QScrollBar:vertical {\n"
"        width: 20px;\n"
"        background: transparent;\n"
"        margin-left: 3px;\n"
"        margin-right: 3px;\n"
"}\n"
"QScrollBar::handle:vertical {\n"
"        width: 20px;\n"
"        min-height: 20px;\n"
"        background: rgb(170, 200, 230);\n"
"        margin-top: 10px;\n"
"        margin-bottom:10px;\n"
"}\n"
"QScrollBar::handle:vertical:hover {\n"
"        background: rgb(165, 195, 225);\n"
"}\n"
"QScrollBar::sub-line:vertical {\n"
"        height:7px;\n"
"        background: rgb(255, 255, 255);\n"
"       \n"
"    image: url(:/pngicon/Resources/up_change.png);\n"
"        subcontrol-position: top;\n"
"}\n"
"QScrollBar::add-line:vertical {\n"
"        height:7px;\n"
"        background: rgb(255, 255, 255);\n"
"     \n"
"    image: url(:/pngicon/Resources/down_change.png);\n"
"        subcontrol-position: bottom;\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {\n"
"        background: rgb(170, 200, 230);\n"
"}\n"
"QScrollBar::add-line:vertical:hover {\n"
"        background: rgb(170, 200, 230);\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"        background: transparent;\n"
"}\n"
"\n"
"QScrollBar#verticalScrollBar:vertical {\n"
"        margin-top: 30px;\n"
"}\n"
"\n"
"/**********下拉列表**********/\n"
"QComboBox {\n"
"        height: 25px;\n"
"        border-radius: 4px;\n"
"        border: 1px solid rgb(111, 156, 207);\n"
"        background: white;\n"
"}\n"
"QComboBox:enabled {\n"
"        color: rgb(84, 84, 84);\n"
"}\n"
"QComboBox:!enabled {\n"
"        color: rgb(80, 80, 80);\n"
"}\n"
"QComboBox:enabled:hover, QComboBox:enabled:focus {\n"
"        color: rgb(51, 51, 51);\n"
"}\n"
"QComboBox::drop-down {\n"
"        width: 20px;\n"
"        border: none;\n"
"        background: transparent;\n"
"}\n"
"QComboBox::drop-down:hover {\n"
"        background: rgba(255, 255, 255, 30);\n"
"}\n"
"QComboBox::down-arrow {\n"
"        image: url(:/toolButton/static/down_show.png);\n"
"        border: 2px solid rgb(255, 255, 255) ; \n"
"         width:15px; \n"
"        height: 11px; \n"
"         background: #5f5f5f; \n"
"        \n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QComboBox::down-arrow:on {\n"
"        /**top: 1px;**/\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"        border: 1px solid rgb(111, 156, 207);\n"
"        background: white;\n"
"        outline: none;\n"
"}\n"
"QComboBox QAbstractItemView::item {\n"
"        height: 25px;\n"
"        color: rgb(73, 73, 73);\n"
"}\n"
"QComboBox QAbstractItemView::item:selected {\n"
"        background: rgb(232, 241, 250);\n"
"        color: rgb(2, 65, 132);\n"
"}\n"
"\n"
"/**********进度条**********/\n"
"/*QProgressBar{\n"
"        border: none;\n"
"        text-align: center;\n"
"        color: white;\n"
"        background: rgb(173, 202, 232);\n"
"}\n"
"QProgressBar::chunk {\n"
"        background: rgb(16, 135, 209);\n"
"}\n"
"\n"
"QProgressBar#progressBar {\n"
"        border: none;\n"
"        text-align: center;\n"
"        color: white;\n"
"        background-color: transparent;\n"
"        background-image: url(\":/White/progressBar\");\n"
"        background-repeat: repeat-x;\n"
"}\n"
"QProgressBar#progressBar::chunk {\n"
"        border: none;\n"
"        background-color: transparent;\n"
"        background-image: url(\":/White/progressBarChunk\");\n"
"        background-repeat: repeat-x;\n"
"}*/\n"
"\n"
"/**********复选框**********/\n"
"QCheckBox{\n"
"        font-weight: bold;\n"
"        spacing: 5px;\n"
"}\n"
"QCheckBox:enabled:checked{\n"
"        color: rgb(2, 65, 132);\n"
"}\n"
"QCheckBox:enabled:!checked{\n"
"        color: rgb(70, 71, 73);\n"
"}\n"
"QCheckBox:enabled:hover{\n"
"        color: rgb(0, 78, 161);\n"
"}\n"
"QCheckBox:!enabled{\n"
"        color: rgb(80, 80, 80);\n"
"}\n"
"QCheckBox::indicator {\n"
"        width: 15px;\n"
"        height:15px;\n"
"}\n"
"\n"
"/**********单选框**********/\n"
"QRadioButton{\n"
"        spacing: 5px;\n"
"}\n"
"QRadioButton:enabled:checked{\n"
"        color: rgb(2, 65, 132);\n"
"}\n"
"QRadioButton:enabled:!checked{\n"
"        color: rgb(70, 71, 73);\n"
"}\n"
"QRadioButton:enabled:hover{\n"
"        color: rgb(0, 78, 161);\n"
"}\n"
"QRadioButton:!enabled{\n"
"        color: rgb(80, 80, 80);\n"
"}\n"
"QRadioButton::indicator {\n"
"        width: 15px;\n"
"        height:15px;\n"
"}\n"
"\n"
"/**********输入框**********/\n"
"QLineEdit {\n"
"        border-radius: 4px;\n"
"        height: 25px;\n"
"        border: 1px solid rgb(111, 156, 207);\n"
"        background: white;\n"
"}\n"
"QLineEdit:enabled {\n"
"        color: rgb(84, 84, 84);\n"
"}\n"
"QLineEdit:enabled:hover, QLineEdit:enabled:focus {\n"
"        color: rgb(51, 51, 51);\n"
"}\n"
"QLineEdit:!enabled {\n"
"        color: rgb(80, 80, 80);\n"
"}\n"
"\n"
"/**********文本编辑框**********/\n"
"QTextEdit {\n"
"        border: 1px solid rgb(111, 156, 207);\n"
"        color: rgb(70, 71, 73);\n"
"        background: rgb(187, 212, 238);\n"
"        \n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"/**********滚动区域**********/\n"
"QScrollArea {\n"
"        border: 1px solid rgb(111, 156, 207);\n"
"        background: rgb(187, 212, 238);\n"
"}\n"
"\n"
"/**********滚动区域**********/\n"
"QWidget#transparentWidget {\n"
"        background: transparent;\n"
"}\n"
"\n"
"/**********微调器**********/\n"
"QSpinBox {\n"
"        border-radius: 4px;\n"
"        height: 24px;\n"
"        min-width: 40px;\n"
"        border: 1px solid rgb(111, 156, 207);\n"
"        background: white;\n"
"}\n"
"QSpinBox:enabled {\n"
"        color: rgb(60, 60, 60);\n"
"}\n"
"QSpinBox:enabled:hover, QSpinBox:enabled:focus {\n"
"        color: rgb(51, 51, 51);\n"
"}\n"
"QSpinBox:!enabled {\n"
"        color: rgb(210, 210, 210);\n"
"        background: transparent;\n"
"}\n"
"QSpinBox::up-button {\n"
"        border-left: 1px solid rgb(111, 156, 207);\n"
"        width: 12px;\n"
"        height: 10px;\n"
"        border-top-right-radius: 4px;\n"
"    image: url(:/toolButton/static/up_change.png);\n"
"}\n"
"QSpinBox::up-button:!enabled {\n"
"        background: transparent;\n"
"}\n"
"QSpinBox::up-button:enabled:hover {\n"
"        background: rgb(255, 255, 255, 30);\n"
"}\n"
"QSpinBox::down-button {\n"
"        border-left: 1px solid rgb(111, 156, 207);\n"
"        width: 12px;\n"
"        height:10px;\n"
"        border-bottom-right-radius: 4px;\n"
"       \n"
"    image: url(:/toolButton/static/down_change.png);\n"
"}\n"
"QSpinBox::down-button:!enabled {\n"
"        background: transparent;\n"
"}\n"
"QSpinBox::down-button:hover {\n"
"        background: rgb(255, 255, 255, 30);\n"
"}\n"
"/**********double微调器**********/\n"
"QDoubleSpinBox {\n"
"        border-radius: 4px;\n"
"        height: 24px;\n"
"        min-width: 40px;\n"
"        border: 1px solid rgb(111, 156, 207);\n"
"        background: white;\n"
"}\n"
"QDoubleSpinBox:enabled {\n"
"        color: rgb(60, 60, 60);\n"
"}\n"
"QDoubleSpinBox:enabled:hover, QSpinBox:enabled:focus {\n"
"        color: rgb(51, 51, 51);\n"
"}\n"
"QDoubleSpinBox:!enabled {\n"
"        color: rgb(210, 210, 210);\n"
"        background: transparent;\n"
"}\n"
"QDoubleSpinBox::up-button {\n"
"        border-left: 1px solid rgb(111, 156, 207);\n"
"        width: 18px;\n"
"        height: 10px;\n"
"        border-top-right-radius: 4px;\n"
"       image: url(:/pngicon/Resources/up_change.png);\n"
"}\n"
"QDoubleSpinBox::up-button:!enabled {\n"
"        background: transparent;\n"
"}\n"
"QDoubleSpinBox::up-button:enabled:hover {\n"
"        background: rgb(255, 255, 255, 30);\n"
"}\n"
"QDoubleSpinBox::down-button {\n"
"        border-left: 1px solid rgb(111, 156, 207);\n"
"        width: 18px;\n"
"        height: 10px;\n"
"        border-bottom-right-radius: 4px;\n"
"       image: url(:/pngicon/Resources/down_change.png);\n"
"}\n"
"QDoubleSpinBox::down-button:!enabled {\n"
"        background: transparent;\n"
"}\n"
"QDoubleSpinBox::down-button:hover {\n"
"        background: rgb(255, 255, 255, 30);\n"
"}\n"
"/**********标签**********/\n"
"QLabel{\n"
"    font-weight: bold;\n"
"}\n"
"QLabel#grayLabel {\n"
"        color: rgb(70, 71, 73);\n"
"}\n"
"\n"
"QLabel#highlightLabel {\n"
"        color: rgb(2, 65, 132);\n"
"}\n"
"\n"
"QLabel#redLabel {\n"
"        color: red;\n"
"}\n"
"\n"
"QLabel#grayYaHeiLabel {\n"
"        color: rgb(175, 175, 175);\n"
"        font-size: 16px;\n"
"}\n"
"\n"
"QLabel#blueLabel {\n"
"        color: rgb(0, 160, 230);\n"
"}\n"
"\n"
"QLabel#listLabel {\n"
"        color: rgb(51, 51, 51);\n"
"}\n"
"\n"
"QLabel#lineBlueLabel {\n"
"        background: rgb(0, 78, 161);\n"
"}\n"
"\n"
"QLabel#graySeperateLabel {\n"
"        background: rgb(200, 220, 230);\n"
"}\n"
"\n"
"QLabel#seperateLabel {\n"
"        background: rgb(112, 153, 194);\n"
"}\n"
"\n"
"QLabel#radiusBlueLabel {\n"
"        border-radius: 15px;\n"
"        color: white;\n"
"        font-size: 16px;\n"
"        background: rgb(0, 78, 161);\n"
"}\n"
"\n"
"QLabel#skinLabel[colorProperty=\"normal\"] {\n"
"        color: rgb(56, 99, 154);\n"
"}\n"
"QLabel#skinLabel[colorProperty=\"highlight\"] {\n"
"        color: rgb(0, 160, 230);\n"
"}\n"
"\n"
"QLabel#informationLabel {\n"
"        qproperty-pixmap: url(:/White/information);\n"
"}\n"
"\n"
"QLabel#errorLabel {\n"
"        qproperty-pixmap: url(:/White/error);\n"
"}\n"
"\n"
"QLabel#successLabel {\n"
"        qproperty-pixmap: url(:/White/success);\n"
"}\n"
"\n"
"QLabel#questionLabel {\n"
"        qproperty-pixmap: url(:/White/question);\n"
"}\n"
"\n"
"QLabel#warningLabel {\n"
"        qproperty-pixmap: url(:/White/warning);\n"
"}\n"
"\n"
"QLabel#groupLabel {\n"
"        color: rgb(56, 99, 154);\n"
"        border: 1px solid rgb(111, 156, 207);\n"
"        font-size: 15px;\n"
"        border-top-color: transparent;\n"
"        border-right-color: transparent;\n"
"        border-left-color: transparent;\n"
"}\n"
"\n"
"/**********按钮**********/\n"
"QPushButton{\n"
"        border-radius: 4px;\n"
"        border: none;\n"
"        width: 75px;\n"
"        height: 25px;\n"
"}\n"
"QPushButton:enabled {\n"
"        background: rgb(120, 170, 220);\n"
"        color: white;\n"
"}\n"
"QPushButton:!enabled {\n"
"        background: rgb(180, 180, 180);\n"
"        color: white;\n"
"}\n"
"QPushButton:enabled:hover{\n"
"        background: rgb(100, 160, 220);\n"
"}\n"
"QPushButton:enabled:pressed{\n"
"        background: rgb(0, 78, 161);\n"
"}\n"
"\n"
"QPushButton#blueButton {\n"
"        color: white;\n"
"}\n"
"QPushButton#blueButton:enabled {\n"
"        background: rgb(0, 78, 161);\n"
"        color: white;\n"
"}\n"
"QPushButton:!enabled {\n"
"        background: rgb(180, 180, 180);\n"
"        color: white;\n"
"}\n"
"QPushButton#blueButton:enabled:hover {\n"
"        background: rgb(2, 65, 132);\n"
"}\n"
"QPushButton#blueButton:enabled:pressed {\n"
"        background: rgb(6, 94, 187);\n"
"}\n"
"\n"
"QPushButton#selectButton {\n"
"        border: none;\n"
"        border-radius: none;\n"
"        border-left: 1px solid rgb(111, 156, 207);\n"
"        background: transparent;\n"
"        image: url(:/White/scan);\n"
"        color: rgb(51, 51, 51);\n"
"}\n"
"QPushButton#selectButton:enabled:hover{\n"
"        background: rgb(187, 212, 238);\n"
"}\n"
"QPushButton#selectButton:enabled:pressed{\n"
"        background: rgb(120, 170, 220);\n"
"}\n"
"\n"
"QPushButton#linkButton {\n"
"        background: transparent;\n"
"        color: rgb(0, 160, 230);\n"
"        text-align:left;\n"
"}\n"
"QPushButton#linkButton:hover {\n"
"        color: rgb(20, 185, 255);\n"
"        text-decoration: underline;\n"
"}\n"
"QPushButton#linkButton:pressed {\n"
"        color: rgb(0, 160, 230);\n"
"}\n"
"\n"
"QPushButton#transparentButton {\n"
"        background: transparent;\n"
"}\n"
"\n"
"/*****************标题栏按钮*******************/\n"
"QPushButton#minimizeButton {\n"
"        border-radius: none;\n"
"        border-bottom-left-radius: 4px;\n"
"        border-bottom-right-radius: 4px;\n"
"        background: rgb(120, 170, 220);\n"
"        image: url(:/White/minimizeHover);\n"
"}\n"
"QPushButton#minimizeButton:hover {\n"
"        image: url(:/White/minimize);\n"
"}\n"
"QPushButton#minimizeButton:pressed {\n"
"        image: url(:/White/minimizePressed);\n"
"}\n"
"\n"
"QPushButton#maximizeButton[maximizeProperty=\"maximize\"] {\n"
"        border-radius: none;\n"
"        border-bottom-left-radius: 4px;\n"
"        border-bottom-right-radius: 4px;\n"
"        background: rgb(120, 170, 220);\n"
"        image: url(:/White/maximizeHover);\n"
"}\n"
"QPushButton#maximizeButton[maximizeProperty=\"maximize\"]:hover {\n"
"        image: url(:/White/maximize);\n"
"}\n"
"QPushButton#maximizeButton[maximizeProperty=\"maximize\"]:pressed {\n"
"        image: url(:/White/maximizePressed);\n"
"}\n"
"\n"
"QPushButton#maximizeButton[maximizeProperty=\"restore\"] {\n"
"        border-radius: none;\n"
"        border-bottom-left-radius: 4px;\n"
"        border-bottom-right-radius: 4px;\n"
"        background: rgb(120, 170, 220);\n"
"        image: url(:/White/restoreHover);\n"
"}\n"
"QPushButton#maximizeButton[maximizeProperty=\"restore\"]:hover {\n"
"        image: url(:/White/restore);\n"
"}\n"
"QPushButton#maximizeButton[maximizeProperty=\"restore\"]:pressed {\n"
"        image: url(:/White/restorePressed);\n"
"}\n"
"\n"
"QPushButton#closeButton {\n"
"        border-radius: none;\n"
"        border-bottom-left-radius: 4px;\n"
"        border-bottom-right-radius: 4px;\n"
"        background: rgb(120, 170, 220);\n"
"        image: url(:/White/closeHover);\n"
"}\n"
"QPushButton#closeButton:hover {\n"
"        image: url(:/White/close);\n"
"}\n"
"QPushButton#closeButton:pressed {\n"
"        image: url(:/White/closePressed);\n"
"}\n"
"\n"
"QPushButton#skinButton {\n"
"        border-radius: none;\n"
"        border-bottom-left-radius: 4px;\n"
"        border-bottom-right-radius: 4px;\n"
"        background: rgb(120, 170, 220);\n"
"        image: url(:/White/skinHover);\n"
"}\n"
"QPushButton#skinButton:hover {\n"
"        image: url(:/White/skin);\n"
"}\n"
"QPushButton#skinButton:pressed {\n"
"        image: url(:/White/skinPressed);\n"
"}\n"
"\n"
"QPushButton#feedbackButton {\n"
"        border-radius: none;\n"
"        border-bottom-left-radius: 4px;\n"
"        border-bottom-right-radius: 4px;\n"
"        background: rgb(120, 170, 220);\n"
"        image: url(:/White/feedbackHover);\n"
"}\n"
"QPushButton#feedbackButton:hover {\n"
"        image: url(:/White/feedback);\n"
"}\n"
"QPushButton#feedbackButton:pressed {\n"
"        image: url(:/White/feedbackPressed);\n"
"}\n"
"\n"
"QPushButton#closeTipButton {\n"
"        border-radius: none;\n"
"        border-image: url(:/White/close);\n"
"        background: transparent;\n"
"}\n"
"QPushButton#closeTipButton:hover {\n"
"        border-image: url(:/White/closeHover);\n"
"}\n"
"QPushButton#closeTipButton:pressed {\n"
"        border-image: url(:/White/closePressed);\n"
"}\n"
"\n"
"QPushButton#changeSkinButton{\n"
"        border-radius: 4px;\n"
"        border: 2px solid rgb(111, 156, 207);\n"
"        background: rgb(204, 227, 252);\n"
"}\n"
"QPushButton#changeSkinButton:hover{\n"
"        border-color: rgb(60, 150, 200);\n"
"}\n"
"QPushButton#changeSkinButton:pressed, QPushButton#changeSkinButton:checked{\n"
"        border-color: rgb(0, 160, 230);\n"
"}\n"
"\n"
"QPushButton#transferButton {\n"
"        padding-left: 5px;\n"
"        padding-right: 5px;\n"
"        color: white;\n"
"        background: rgb(0, 78, 161);\n"
"}\n"
"QPushButton#transferButton:hover {\n"
"        background: rgb(2, 65, 132);\n"
"}\n"
"QPushButton#transferButton:pressed {\n"
"        background: rgb(6, 94, 187);\n"
"}\n"
"QPushButton#transferButton[iconProperty=\"left\"] {\n"
"        qproperty-icon: url(:/White/left);\n"
"}\n"
"QPushButton#transferButton[iconProperty=\"right\"] {\n"
"        qproperty-icon: url(:/White/right);\n"
"}\n"
"\n"
"QPushButton#openButton {\n"
"        border-radius: none;\n"
"        image: url(:/White/open);\n"
"        background: transparent;\n"
"}\n"
"QPushButton#openButton:hover {\n"
"        image: url(:/White/openHover);\n"
"}\n"
"QPushButton#openButton:pressed {\n"
"        image: url(:/White/openPressed);\n"
"}\n"
"\n"
"QPushButton#deleteButton {\n"
"        border-radius: none;\n"
"        image: url(:/White/delete);\n"
"        background: transparent;\n"
"}\n"
"QPushButton#deleteButton:hover {\n"
"        image: url(:/White/deleteHover);\n"
"}\n"
"QPushButton#deleteButton:pressed {\n"
"        image: url(:/White/deletePressed);\n"
"}\n"
"\n"
"QPushButton#menuButton {\n"
"        text-align: left center;\n"
"        padding-left: 3px;\n"
"        color: rgb(84, 84, 84);\n"
"        border: 1px solid rgb(111, 156, 207);\n"
"        background: white;\n"
"}\n"
"QPushButton#menuButton::menu-indicator{\n"
"        subcontrol-position: right center;\n"
"        subcontrol-origin: padding;\n"
"        image: url(:/White/arrowBottom);\n"
"        padding-right: 3px;\n"
"}\n"
"\n"
"QToolButton{\n"
"\n"
"border:none;\n"
"border-radius: 10px;\n"
"padding-top:4px;\n"
"\n"
" font:9pt \"Arial\";\n"
"    font: 75 9pt \"Adobe Caslon Pro Bold\";\n"
" }\n"
"\n"
"\n"
" QToolButton#m_toolButtonAdd{\n"
"     margin-left:5px;\n"
"     background:url(:/Resources/add.png) center no-repeat;\n"
" }\n"
"\n"
"\n"
" QToolButton#m_toolButtonAdd:hover{\n"
"background-color:\"#d4d4d4\";\n"
"\n"
" }\n"
"\n"
"\n"
" QToolButton#m_toolButtonAdd:pressed{\n"
"background-color:\"#bdbdbd\";\n"
" }\n"
"\n"
"\n"
" QToolButton#m_toolButtonAdd:disabled{\n"
"background:url(:/Resources/add_icon_disabled.png) center no-repeat;\n"
" } \n"
"\n"
"/**********按钮**********/\n"
"QToolButton#nsccButton {\n"
"        border: none;\n"
"        color: rgb(2, 65, 132);\n"
"        background: transparent;\n"
"        padding: 10px;\n"
"        qproperty-icon: url(:/White/nscc);\n"
"        qproperty-iconSize: 32px 32px;\n"
"        qproperty-toolButtonStyle: ToolButtonTextUnderIcon;\n"
"}\n"
"QToolButton#nsccButton:hover {\n"
"        background: rgb(187, 212, 238);\n"
"            \n"
"    background-color: rgb(0, 255, 255);\n"
"}\n"
"\n"
"QToolButton#transferButton {\n"
"        border: none;\n"
"        color: rgb(2, 65, 132);\n"
"        background: transparent;\n"
"        padding: 10px;\n"
"        qproperty-icon: url(:/White/transfer);\n"
"        qproperty-iconSize: 32px 32px;\n"
"        qproperty-toolButtonStyle: ToolButtonTextUnderIcon;\n"
"}\n"
"QToolButton#transferButton:hover {\n"
"        /*background: rgb(187, 212, 238);*/\n"
"    background-color: rgb(0, 255, 255);\n"
"}\n"
"QToolButton::hover {\n"
"        /*background: rgb(187, 212, 238);*/\n"
"    \n"
"    background-color: rgb(187, 212, 238);\n"
"}\n"
" QToolButton::pressed{\n"
"background-color:\"#bdbdbd\";\n"
" }")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setMinimumSize(QtCore.QSize(0, 120))
        self.tabWidget.setMaximumSize(QtCore.QSize(16777215, 120))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.layoutWidget = QtWidgets.QWidget(self.tab)
        self.layoutWidget.setGeometry(QtCore.QRect(19, 12, 485, 78))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.comboBox_cameraDeviceList = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_cameraDeviceList.setMinimumSize(QtCore.QSize(120, 23))
        self.comboBox_cameraDeviceList.setMaximumSize(QtCore.QSize(120, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_cameraDeviceList.setFont(font)
        self.comboBox_cameraDeviceList.setObjectName("comboBox_cameraDeviceList")
        self.verticalLayout_4.addWidget(self.comboBox_cameraDeviceList)
        self.checkBox_saveVideo = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_saveVideo.setMinimumSize(QtCore.QSize(72, 0))
        self.checkBox_saveVideo.setMaximumSize(QtCore.QSize(120, 16777215))
        self.checkBox_saveVideo.setStyleSheet("")
        self.checkBox_saveVideo.setObjectName("checkBox_saveVideo")
        self.verticalLayout_4.addWidget(self.checkBox_saveVideo)
        self.horizontalLayout_6.addLayout(self.verticalLayout_4)
        self.toolButton_scanCamera = QtWidgets.QToolButton(self.layoutWidget)
        self.toolButton_scanCamera.setStyleSheet("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/toolButton/static/scanCamera.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_scanCamera.setIcon(icon)
        self.toolButton_scanCamera.setIconSize(QtCore.QSize(50, 50))
        self.toolButton_scanCamera.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_scanCamera.setObjectName("toolButton_scanCamera")
        self.horizontalLayout_6.addWidget(self.toolButton_scanCamera)
        self.toolButton_openCamera = QtWidgets.QToolButton(self.layoutWidget)
        self.toolButton_openCamera.setStyleSheet("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/toolButton/static/camera.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_openCamera.setIcon(icon1)
        self.toolButton_openCamera.setIconSize(QtCore.QSize(50, 50))
        self.toolButton_openCamera.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_openCamera.setObjectName("toolButton_openCamera")
        self.horizontalLayout_6.addWidget(self.toolButton_openCamera)
        self.toolButton_closeCamera = QtWidgets.QToolButton(self.layoutWidget)
        self.toolButton_closeCamera.setStyleSheet("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/toolButton/static/closeCamera.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_closeCamera.setIcon(icon2)
        self.toolButton_closeCamera.setIconSize(QtCore.QSize(50, 50))
        self.toolButton_closeCamera.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_closeCamera.setObjectName("toolButton_closeCamera")
        self.horizontalLayout_6.addWidget(self.toolButton_closeCamera)
        self.line = QtWidgets.QFrame(self.layoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_6.addWidget(self.line)
        self.toolButton_changeDir = QtWidgets.QToolButton(self.layoutWidget)
        self.toolButton_changeDir.setStyleSheet("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/toolButton/static/dir.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_changeDir.setIcon(icon3)
        self.toolButton_changeDir.setIconSize(QtCore.QSize(50, 50))
        self.toolButton_changeDir.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_changeDir.setObjectName("toolButton_changeDir")
        self.horizontalLayout_6.addWidget(self.toolButton_changeDir)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.layoutWidget1 = QtWidgets.QWidget(self.tab_2)
        self.layoutWidget1.setGeometry(QtCore.QRect(19, 10, 975, 75))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_5.setMinimumSize(QtCore.QSize(36, 0))
        self.label_5.setMaximumSize(QtCore.QSize(36, 16777215))
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.spinBox_trainRate = QtWidgets.QSpinBox(self.layoutWidget1)
        self.spinBox_trainRate.setMinimumSize(QtCore.QSize(42, 23))
        self.spinBox_trainRate.setMaximumSize(QtCore.QSize(42, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.spinBox_trainRate.setFont(font)
        self.spinBox_trainRate.setMaximum(100)
        self.spinBox_trainRate.setProperty("value", 80)
        self.spinBox_trainRate.setObjectName("spinBox_trainRate")
        self.horizontalLayout_3.addWidget(self.spinBox_trainRate)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_7.setMinimumSize(QtCore.QSize(8, 0))
        self.label_7.setMaximumSize(QtCore.QSize(8, 16777215))
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_3.addWidget(self.label_7)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_8 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_8.setMinimumSize(QtCore.QSize(36, 0))
        self.label_8.setMaximumSize(QtCore.QSize(36, 16777215))
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_4.addWidget(self.label_8)
        self.spinBox_frameGap = QtWidgets.QSpinBox(self.layoutWidget1)
        self.spinBox_frameGap.setMinimumSize(QtCore.QSize(42, 23))
        self.spinBox_frameGap.setMaximumSize(QtCore.QSize(42, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.spinBox_frameGap.setFont(font)
        self.spinBox_frameGap.setMaximum(100)
        self.spinBox_frameGap.setProperty("value", 10)
        self.spinBox_frameGap.setObjectName("spinBox_frameGap")
        self.horizontalLayout_4.addWidget(self.spinBox_frameGap)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_9.setMinimumSize(QtCore.QSize(8, 0))
        self.label_9.setMaximumSize(QtCore.QSize(8, 16777215))
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_4.addWidget(self.label_9)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5.addLayout(self.verticalLayout_3)
        self.toolButton_datasetClip = QtWidgets.QToolButton(self.layoutWidget1)
        self.toolButton_datasetClip.setStyleSheet("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/toolButton/static/datasetClip.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_datasetClip.setIcon(icon4)
        self.toolButton_datasetClip.setIconSize(QtCore.QSize(50, 50))
        self.toolButton_datasetClip.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_datasetClip.setObjectName("toolButton_datasetClip")
        self.horizontalLayout_5.addWidget(self.toolButton_datasetClip)
        self.toolButton_clipVideo = QtWidgets.QToolButton(self.layoutWidget1)
        self.toolButton_clipVideo.setStyleSheet("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/toolButton/static/clipVideo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_clipVideo.setIcon(icon5)
        self.toolButton_clipVideo.setIconSize(QtCore.QSize(50, 50))
        self.toolButton_clipVideo.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_clipVideo.setObjectName("toolButton_clipVideo")
        self.horizontalLayout_5.addWidget(self.toolButton_clipVideo)
        self.line_3 = QtWidgets.QFrame(self.layoutWidget1)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout_5.addWidget(self.line_3)
        self.toolButton_generateAnnotation = QtWidgets.QToolButton(self.layoutWidget1)
        self.toolButton_generateAnnotation.setStyleSheet("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/toolButton/static/generateAnnotaton.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_generateAnnotation.setIcon(icon6)
        self.toolButton_generateAnnotation.setIconSize(QtCore.QSize(50, 50))
        self.toolButton_generateAnnotation.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_generateAnnotation.setObjectName("toolButton_generateAnnotation")
        self.horizontalLayout_5.addWidget(self.toolButton_generateAnnotation)
        self.toolButton_checkFromJson = QtWidgets.QToolButton(self.layoutWidget1)
        self.toolButton_checkFromJson.setStyleSheet("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/toolButton/static/json.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_checkFromJson.setIcon(icon7)
        self.toolButton_checkFromJson.setIconSize(QtCore.QSize(50, 50))
        self.toolButton_checkFromJson.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_checkFromJson.setObjectName("toolButton_checkFromJson")
        self.horizontalLayout_5.addWidget(self.toolButton_checkFromJson)
        self.toolButton_jsonToTxt = QtWidgets.QToolButton(self.layoutWidget1)
        self.toolButton_jsonToTxt.setStyleSheet("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/toolButton/static/jsontotxt.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_jsonToTxt.setIcon(icon8)
        self.toolButton_jsonToTxt.setIconSize(QtCore.QSize(50, 50))
        self.toolButton_jsonToTxt.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_jsonToTxt.setObjectName("toolButton_jsonToTxt")
        self.horizontalLayout_5.addWidget(self.toolButton_jsonToTxt)
        self.toolButton_checkFromTxt = QtWidgets.QToolButton(self.layoutWidget1)
        self.toolButton_checkFromTxt.setStyleSheet("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/toolButton/static/txt.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_checkFromTxt.setIcon(icon9)
        self.toolButton_checkFromTxt.setIconSize(QtCore.QSize(50, 50))
        self.toolButton_checkFromTxt.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_checkFromTxt.setObjectName("toolButton_checkFromTxt")
        self.horizontalLayout_5.addWidget(self.toolButton_checkFromTxt)
        self.toolButton_checkLastImg = QtWidgets.QToolButton(self.layoutWidget1)
        self.toolButton_checkLastImg.setStyleSheet("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/toolButton/static/last.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_checkLastImg.setIcon(icon10)
        self.toolButton_checkLastImg.setIconSize(QtCore.QSize(50, 50))
        self.toolButton_checkLastImg.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_checkLastImg.setObjectName("toolButton_checkLastImg")
        self.horizontalLayout_5.addWidget(self.toolButton_checkLastImg)
        self.toolButton_checkNextImg = QtWidgets.QToolButton(self.layoutWidget1)
        self.toolButton_checkNextImg.setStyleSheet("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/toolButton/static/next.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_checkNextImg.setIcon(icon11)
        self.toolButton_checkNextImg.setIconSize(QtCore.QSize(50, 50))
        self.toolButton_checkNextImg.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_checkNextImg.setObjectName("toolButton_checkNextImg")
        self.horizontalLayout_5.addWidget(self.toolButton_checkNextImg)
        self.toolButton_generateImgList = QtWidgets.QToolButton(self.layoutWidget1)
        self.toolButton_generateImgList.setStyleSheet("")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/toolButton/static/generateImgList.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_generateImgList.setIcon(icon12)
        self.toolButton_generateImgList.setIconSize(QtCore.QSize(50, 50))
        self.toolButton_generateImgList.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_generateImgList.setObjectName("toolButton_generateImgList")
        self.horizontalLayout_5.addWidget(self.toolButton_generateImgList)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.spinBox_allcheck = QtWidgets.QSpinBox(self.layoutWidget1)
        self.spinBox_allcheck.setMinimumSize(QtCore.QSize(42, 0))
        self.spinBox_allcheck.setMaximumSize(QtCore.QSize(35, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.spinBox_allcheck.setFont(font)
        self.spinBox_allcheck.setObjectName("spinBox_allcheck")
        self.horizontalLayout_2.addWidget(self.spinBox_allcheck)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget1)
        self.label.setMinimumSize(QtCore.QSize(16, 0))
        self.label.setMaximumSize(QtCore.QSize(16, 16777215))
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.label_checkImgIndex = QtWidgets.QLabel(self.layoutWidget1)
        self.label_checkImgIndex.setMinimumSize(QtCore.QSize(16, 0))
        self.label_checkImgIndex.setMaximumSize(QtCore.QSize(16, 16777215))
        self.label_checkImgIndex.setObjectName("label_checkImgIndex")
        self.horizontalLayout.addWidget(self.label_checkImgIndex)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_3.setMinimumSize(QtCore.QSize(16, 0))
        self.label_3.setMaximumSize(QtCore.QSize(16, 16777215))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_4.setMinimumSize(QtCore.QSize(20, 0))
        self.label_4.setMaximumSize(QtCore.QSize(20, 16777215))
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.label_num_of_allcheck = QtWidgets.QLabel(self.layoutWidget1)
        self.label_num_of_allcheck.setMinimumSize(QtCore.QSize(16, 0))
        self.label_num_of_allcheck.setMaximumSize(QtCore.QSize(16, 16777215))
        self.label_num_of_allcheck.setObjectName("label_num_of_allcheck")
        self.horizontalLayout.addWidget(self.label_num_of_allcheck)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_6.setMinimumSize(QtCore.QSize(16, 0))
        self.label_6.setMaximumSize(QtCore.QSize(16, 16777215))
        self.label_6.setObjectName("label_6")
        self.horizontalLayout.addWidget(self.label_6)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_5.addLayout(self.verticalLayout_2)
        self.line_2 = QtWidgets.QFrame(self.layoutWidget1)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_5.addWidget(self.line_2)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.label_imgShow = QtWidgets.QLabel(self.centralwidget)
        self.label_imgShow.setMinimumSize(QtCore.QSize(920, 500))
        self.label_imgShow.setStyleSheet("background-color: rgb(235, 253, 255);\n"
"color: rgb(170, 255, 255);")
        self.label_imgShow.setObjectName("label_imgShow")
        self.verticalLayout.addWidget(self.label_imgShow)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1063, 33))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpenFile = QtWidgets.QAction(MainWindow)
        self.actionOpenFile.setObjectName("actionOpenFile")
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.menuFile.addAction(self.actionOpenFile)
        self.menuFile.addAction(self.actionClose)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.checkBox_saveVideo.setText(_translate("MainWindow", "保存视频"))
        self.toolButton_scanCamera.setText(_translate("MainWindow", "扫描相机"))
        self.toolButton_openCamera.setText(_translate("MainWindow", "打开相机"))
        self.toolButton_closeCamera.setText(_translate("MainWindow", "关闭相机"))
        self.toolButton_changeDir.setText(_translate("MainWindow", "更改目录"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "视频采集"))
        self.label_5.setText(_translate("MainWindow", "Train:"))
        self.label_7.setText(_translate("MainWindow", "%"))
        self.label_8.setText(_translate("MainWindow", "F Gap:"))
        self.label_9.setText(_translate("MainWindow", "f"))
        self.toolButton_datasetClip.setText(_translate("MainWindow", "数据分割"))
        self.toolButton_clipVideo.setText(_translate("MainWindow", "间隔抽帧"))
        self.toolButton_generateAnnotation.setText(_translate("MainWindow", "生成标注"))
        self.toolButton_checkFromJson.setText(_translate("MainWindow", "Json验证"))
        self.toolButton_jsonToTxt.setText(_translate("MainWindow", "JsonToTxt"))
        self.toolButton_checkFromTxt.setText(_translate("MainWindow", "TXT验证"))
        self.toolButton_checkLastImg.setText(_translate("MainWindow", "显示上张"))
        self.toolButton_checkNextImg.setText(_translate("MainWindow", "显示下张"))
        self.toolButton_generateImgList.setText(_translate("MainWindow", "生成列表"))
        self.label_2.setText(_translate("MainWindow", "校验数目："))
        self.label.setText(_translate("MainWindow", "第"))
        self.label_checkImgIndex.setText(_translate("MainWindow", "0"))
        self.label_3.setText(_translate("MainWindow", "张"))
        self.label_4.setText(_translate("MainWindow", "/共"))
        self.label_num_of_allcheck.setText(_translate("MainWindow", "0"))
        self.label_6.setText(_translate("MainWindow", "张"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "视频处理"))
        self.label_imgShow.setText(_translate("MainWindow", "DisplayArea"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionOpenFile.setText(_translate("MainWindow", "Open"))
        self.actionClose.setText(_translate("MainWindow", "Close"))
import toolButtonIcon_rc
